privacy-ethereum/maci

- app/contract-interactions.js
- app/index.js
- app/scanner.js
- contracts/MACI.sol
- maci-config.js
- package.json
Added code snippet example on how to scan through contract transaction history and create merkletree (preparing merklettree states before inserting into snark circuit)
> Scan Through Contract Tx History and Recreate merkletree

- SPEC.md
Try to give an update on spec.
Photo by David Clode on Unsplash
> Spec review 1: before state root transition proof circuit

- cli/ts/process.ts
- cli/ts/tally.ts
- config/tsconfig.json
- contracts/package.json
- crypto/ts/index.ts
- crypto/tsconfig.json
- domainobjs/ts/__tests__/DomainObjs.test.ts
- domainobjs/ts/index.ts
- domainobjs/tsconfig.json
For issue #127
Enabled generation of .d.ts files for several packages:
- maci-config
- maci-crypto
- maci-domainobjs
Fixed some bugs that were discovered by typescript compiler.
> Add type definitions

- contracts/ts/__tests__/IncrementalMerkleTree.test.ts
- contracts/ts/__tests__/IncrementalQuinTree.test.ts
- contracts/ts/__tests__/VerifyTally.test.ts
This PR is a minor change which I want to use to investigate a problem with Travis CI.
> Removed unused vars in some test files

- cli/ts/index.ts
Similar to `processMessages` and `tally`, these functions could be imported by external tools.
> Export 'processAndTallyWithoutProofs' and 'verify' functions

- contracts/sol/MACI.sol
- contracts/ts/deploy.ts
This makes it easier for the clrfund contracts to work with the MACI contract.
> Replace Ownable with coordinatorAddress for coordinatorReset

- contracts/contracts/MACI.sol
Closes #260 
I'd include a testcase and revert reason, but it takes far too long to create so many users given our current implementation.
> Change signups check to new calculation

- core/README.md
- crypto/README.md
- domainobjs/README.md
> Update readme files for some modules

- contracts/contracts/Poll.sol
https://github.com/appliedzkp/maci/issues/272
> Fix comments in Poll.sol (lines 399 - 405)

- contracts/contracts/Poll.sol
- integrationTests/ts/__tests__/suites.json
Closes #261 
But let's hold on merge until we address the tally votes circuits issues as the write up of the logic would change in the issue
> Fix tally for Poll contract

- contracts/contracts/Poll.sol
- contracts/ts/__tests__/MACI.test.ts
> Ensure subtrees merged prior for MaciStateAq

- Dockerfile
> fix: install wget in DockerFile

- cli/testCheckKeys.sh
- cli/ts/checkVerifyingKey.ts
- cli/ts/index.ts
- cli/ts/setVerifyingKeys.ts
> Check verifying keys command

- circuits/circom/batchUpdateStateTree.circom
- circuits/circom/hasherPoseidon.circom
- circuits/circom/updateStateTree.circom
typo causes rust compiler to fail
> Lint circom files causing rust compiler error

- circuits/package-lock.json
- cli/package-lock.json
- cli/ts/checkVerifyingKey.ts
- cli/ts/deployPoll.ts
- cli/ts/proveOnChain.ts
- cli/ts/publish.ts
- cli/ts/verify.ts
- contracts/package-lock.json
- contracts/ts/genEmptyBallotRootsContract.ts
- core/package-lock.json
- core/ts/MaciState.ts
- crypto/package-lock.json
- crypto/ts/AccQueue.ts
- crypto/ts/index.ts
- domainobjs/package-lock.json
- domainobjs/ts/__tests__/DomainObjs.test.ts
- domainobjs/ts/index.ts
- integrationTests/package-lock.json
- integrationTests/ts/__tests__/user.ts
- package-lock.json
- server/package-lock.json
- tsconfig.json
> Fix BigInt issues with new typescript version

- circuits/circom/processMessages.circom
> Reconstruct state root before processing batch

- README.md
Updating the git ssh command. It was pointing out to the old repo
> Updated the command of pulling the repo

- .github/workflows/circuit-build.yml
- .github/workflows/e2e-nightly-test.yml
- .github/workflows/e2e.yml
Related release note: https://github.com/iden3/circom/commit/8a97f51dfb955b867f33a447b707dd445e5e15b1
> Bump the circom to v2.0.5

- .github/workflows/e2e-nightly-test.yml
This PR fixes a missing hardhat network preparation before running e2e test in nightly test workflow.
> Fix a nightly test

- cli/ts/setVerifyingKeys.ts
- integrationTests/ts/__tests__/suites.ts
* add missing error handling in test flow in integration test harness
* remove redundant code in integration test harness
* fail earlier when the file doesn't exist in given path
* check .zkey file first before extract verification key
> fix: missing error handling in test harness

- README.md
- circuits/scripts/buildBatchUpdateStateTreeSnark.sh
- circuits/scripts/buildCustomSnarks.sh
- circuits/scripts/buildQuadVoteTallySnark.sh
- circuits/scripts/buildSnarks32.sh
- circuits/scripts/buildSnarks32BatchSize16.sh
- circuits/scripts/buildSnarks32BatchSize256.sh
- circuits/scripts/buildSnarksLarge.sh
- circuits/scripts/buildSnarksMedium.sh
- circuits/scripts/buildSnarksSmall.sh
Fixes https://github.com/privacy-scaling-explorations/maci/issues/546
Also fixes minor typo in readme
> Fix missing memory_limit parameter

- contracts/ts/deploy.ts
- contracts/ts/utils.ts
Refactored deployment scripts to be more concise
fix #555
> refactor(contracts): refactoring deployment scripts

- README.md
- circuits/README.md
- cli/README.md
- common/README.md
- contracts/README.md
- core/README.md
- crypto/README.md
- domainobjs/README.md
- integrationTests/README.md
- server/README.md
This PR introduce a badges displays latest npm version of each package, CI status and etc.
> Add a badges to README.md

- circuits/circom/subsidy.circom
- cli/ts/proveOnChain.ts
- contracts/contracts/Poll.sol
- core/ts/MaciState.ts
Reduce the number of batches for subsidy calculation by around one half
> improve subsidy calculation performance

- contracts/contracts/Subsidy.sol
- contracts/contracts/Tally.sol
add onlyOwner modifier to updateSbCommitment
> constraint updatesbcommitment in contracts

- circuits/circom/isDeactivatedKey.circom
- circuits/circom/test/isDeactivatedKey_test.circom
- circuits/circomHelperConfig.json
- circuits/package.json
- circuits/ts/__tests__/KeyDeactivation.test.ts
Circuit for verifying the inclusion of the keys in the deactivated keys set.
> Deactivated keys set circuit

- docs/elgamal-general.md
General documentation of the ElGamal protocol upgrade
> ElGamal general documentation

- README.md
- circuits/README.md
This documentation update is intended to make the project more accessible and easier to build for new contributors or users, promoting a better understanding of the project structure and its dependencies.
> Update README.md of `circuits` package with build instructions

- contracts/contracts/MACI.sol
> Fix: return new poll address

- old_specs/02_contract.md
See https://github.com/privacy-scaling-explorations/maci/pull/535#issuecomment-1768331768
> Update 02_contract.md - small anchor fix

- README.md
- docs/audit.md
- docs/circuits.md
- docs/contracts.md
- docs/primitives.md
- docs/testing.md
- docs/trustedsetup.md
- old_specs/faq.md
Fix: typos
@samajammin Hey, I closed the previous PR (https://github.com/privacy-scaling-explorations/maci/pull/598) and checked the newer docs
> Fix: typos

- circuits/scripts/build.sh
- circuits/scripts/downloadTestCircuits.sh
- circuits/ts/index.ts
- circuits/ts/snarkjs.d.ts
- cli/tests/prepare_test.sh
- cli/ts/genProofs.ts
modify proof generation code and related tests to ensure MACI can be run on any architecture
fix #814
> feat(cross-platform-maci) - Allow MACI to run e2e on any architecture

- circuits/ts/__tests__/Hasher.test.ts
- circuits/ts/__tests__/MessageToCommand.test.ts
- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- contracts/tests/HasherBenchmarks.test.ts
- contracts/tests/MACI.test.ts
- contracts/tests/MACI_overflow.test.ts
- contracts/ts/deploy.ts
- contracts/ts/genMaciState.ts
- contracts/ts/utils.ts
- core/ts/MaciState.ts
- core/ts/__tests__/ProcessMessage.test.ts
- crypto/ts/AccQueue.ts
- crypto/ts/crypto.ts
- domainobjs/ts/index.ts
- integrationTests/ts/__tests__/deployPollWithRandomSigner.test.ts
- integrationTests/ts/__tests__/suitesUtils.ts
- integrationTests/ts/__tests__/utils.ts
Fixes: https://github.com/privacy-scaling-explorations/maci/issues/457
> refactor: fix ESLint issues

- website/src/components/HomepageFeatures/index.tsx
Working with the design team on building illustrations for these features, so wanted to quickly update these
> feat: update features on homepage

- website/versioned_docs/version-v1.x/spec.md
- website/versioned_docs/version-v1.x/troubleshooting.md
This PR add MACI 1.0 spec to website
> docs: add 1.0 spec

- .github/workflows/nightly.yml
- .github/workflows/reusable-e2e.yml
- core/ts/MaciState.ts
- core/ts/Poll.ts
- domainobjs/.eslintrc.js
- domainobjs/package.json
- domainobjs/ts/__tests__/ballot.test.ts
- domainobjs/ts/__tests__/commands.test.ts
- domainobjs/ts/__tests__/keypair.test.ts
- domainobjs/ts/__tests__/privateKey.test.ts
- domainobjs/ts/__tests__/publicKey.test.ts
- domainobjs/ts/__tests__/stateLeaf.test.ts
- domainobjs/ts/__tests__/verifyingKey.test.ts
- domainobjs/ts/ballot.ts
- domainobjs/ts/commands/PCommand.ts
- domainobjs/ts/commands/TCommand.ts
- domainobjs/ts/commands/index.ts
- domainobjs/ts/commands/types.ts
- domainobjs/ts/constants.ts
- domainobjs/ts/index.ts
- domainobjs/ts/keyPair.ts
- domainobjs/ts/message.ts
- domainobjs/ts/privateKey.ts
- domainobjs/ts/publicKey.ts
- domainobjs/ts/stateLeaf.ts
- domainobjs/ts/types.ts
- domainobjs/ts/verifyingKey.ts
- domainobjs/tsconfig.json
Blocked by #873
Related to #845
> chore(domainobjs): apply linter rules and fixes

- core/package-lock.json
- core/package.json
This PR publish a declaration file of core package
> chore(core): publish a declaration file

- cli/.gitignore
- cli/ts/commands/genLocalState.ts
- cli/ts/commands/genProofs.ts
- cli/ts/commands/signup.ts
- cli/ts/commands/verify.ts
- cli/ts/index.ts
- website/versioned_docs/version-v1.x/cli.md
> fix(cli): ui and documentation fixes

- .github/workflows/release.yml
This PR reflects the latest update of build process
> ci: update npm publish workflow

- .github/workflows/checks.yml
- .github/workflows/circuit-build.yml
- website/versioned_docs/version-v0.x/faq.md
- website/versioned_docs/version-v0.x/introduction.md
- website/versioned_docs/version-v1.x/contracts.md
- website/versioned_docs/version-v1.x/primitives.md
In reference to us establishing GH processes #757 - we decided to keep only one main branch: dev. This PR consolidates master into dev using a rebase so that it can be safely deleted.
> chore(repo): branch consolidation

- website/versioned_docs/version-v1.x/contracts.md
- website/versioned_docs/version-v1.x/introduction.md
- website/versioned_docs/version-v1.x/primitives.md
- website/versioned_docs/version-v1.x/spec.md
minor typo fix in what I believe are the docs, hope I'm not wrong, I'm not familiar with the struct
have a nice sunday
> chore(website/versioned_docs/version-v1.x): typo fix

- .github/pull_request_template.md
> fix: update broken GH links

- website/src/pages/roadmap.md
Shortened this up to focus on core priorities & tighten language
#857
> chore(website): cut down /roadmap length

- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- circuits/ts/types/snarkjs.d.ts
- contracts/tests/MACI.test.ts
- contracts/tests/MessageProcessor.test.ts
- contracts/tests/Poll.test.ts
- contracts/tests/Tally.test.ts
- contracts/ts/genMaciState.ts
- core/ts/MaciState.ts
- core/ts/Poll.ts
- core/ts/__tests__/MaciState.test.ts
- core/ts/__tests__/constants.ts
- core/ts/__tests__/utils.ts
- core/ts/utils/errors.ts
- core/ts/utils/types.ts
- integrationTests/ts/__tests__/integration.test.ts
> refactor(core): refactor the process message functions and general cleanup

- core/ts/Poll.ts
- core/ts/__tests__/MaciState.test.ts
Add unit tests for the functions involved with processing messages in the Poll TS code.
This build over PR: #914 (needs to be merged first)
Re: #792
> test(core): process messages unit tests

- crypto/package.json
- crypto/ts/__tests__/Crypto.test.ts
- crypto/ts/crypto.ts
- crypto/ts/index.ts
- crypto/ts/utils.ts
Add unit tests for functions within the crypto package and fix errors that arised by the test cases. Note that babyJubAddPoint seem to not work, however this is not used by the codebase
fix #928
> test(crypto): complete unit tests for the crypto package

- circuits/.eslintrc.js
- circuits/package.json
- circuits/ts/__tests__/CalculateTotal.test.ts
- circuits/ts/__tests__/CeremonyParams.test.ts
- circuits/ts/__tests__/Ecdh.test.ts
- circuits/ts/__tests__/Hasher.test.ts
- circuits/ts/__tests__/MessageToCommand.test.ts
- circuits/ts/__tests__/MessageValidator.test.ts
- circuits/ts/__tests__/PrivToPubKey.test.ts
- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/__tests__/Splicer.test.ts
- circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- circuits/ts/__tests__/UnpackElement.test.ts
- circuits/ts/__tests__/VerifySignature.test.ts
- circuits/ts/__tests__/utils/utils.ts
- circuits/ts/proofs.ts
- circuits/ts/types.ts
- circuits/ts/types/circom_tester.d.ts
- circuits/ts/types/snarkjs.d.ts
- circuits/ts/utils.ts
- circuits/tsconfig.json
> chore(circuits): integrate linter

- cli/tests/e2e.subsidy.test.ts
- cli/tests/e2e.test.ts
> fix(test-cli): test fix

- circuits/ts/__tests__/CeremonyParams.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- cli/ts/commands/genProofs.ts
- contracts/tests/MessageProcessor.test.ts
- contracts/tests/Subsidy.test.ts
- contracts/tests/Tally.test.ts
- core/ts/Poll.ts
- core/ts/__tests__/MaciState.test.ts
- core/ts/index.ts
- core/ts/utils/types.ts
- core/ts/utils/utils.ts
- integrationTests/package.json
Refactor the last few functions left inside the Poll.ts file, as well as add interfaces for circuit inputs
re #792
> refactor(core): refactor the core package subsidy and tally functions

- core/package.json
- core/ts/__tests__/MaciState.test.ts
- core/ts/__tests__/Poll.test.ts
- core/ts/__tests__/utils.test.ts
Refactor and add tests to the core package.
Blocked by #953 
re: #792
> test(core): test refactoring and implementation

- .github/workflows/checks.yml
- .husky/pre-commit
- circuits/package.json
- cli/package.json
- contracts/package.json
- core/package.json
- crypto/package.json
- domainobjs/package.json
- integrationTests/package.json
- package.json
- website/package-lock.json
- website/package.json
> chore: add types check

- integrationTests/ts/__tests__/data/suites.json
- integrationTests/ts/__tests__/utils/interfaces.ts
- integrationTests/ts/__tests__/utils/utils.ts
- website/versioned_docs/version-v1.x/audit.md
- website/versioned_docs/version-v1.x/ci-pipeline.md
- website/versioned_docs/version-v1.x/coordinator-processing.md
- website/versioned_docs/version-v1.x/integrating.md
- website/versioned_docs/version-v1.x/key-change.md
- website/versioned_docs/version-v1.x/spec.md
- website/versioned_docs/version-v1.x/testing-in-details.md
- website/versioned_docs/version-v1.x/testing.md
- website/versioned_docs/version-v1.x/troubleshooting.md
- website/versioned_docs/version-v1.x/versioning.md
Revisit documentation around testing.
fix #891
> docs(testing): revisit testing docs and add more detailed info

- circuits/package-lock.json
- circuits/package.json
- cli/package-lock.json
- cli/package.json
- cli/ts/commands/genProofs.ts
- cli/ts/utils/interfaces.ts
- contracts/package-lock.json
- contracts/package.json
- core/package-lock.json
- crypto/package-lock.json
- domainobjs/package-lock.json
- integrationTests/package-lock.json
- integrationTests/package.json
- package-lock.json
- package.json
- website/package-lock.json
Remove redundant dependencies, run `npm audit` and upgrade what is possible. 
Depends on #961 being merged first
re: #793
> chore(deps): update project dependencies and remove redundant ones

- .github/workflows/contracts-build.yml
- .github/workflows/e2e.yml
- .github/workflows/nightly-ceremony.yml
- .github/workflows/release.yml
- circuits/package-lock.json
- circuits/ts/__tests__/utils/constants.ts
- cli/package-lock.json
- contracts/package-lock.json
- contracts/scripts/compileSol.sh
- contracts/scripts/writeEmptyBallotRoots.sh
- contracts/tests/MACI.test.ts
- contracts/tests/MessageProcessor.test.ts
- contracts/tests/SignUpGatekeeper.test.ts
- contracts/ts/genEmptyBallotRootsContract.ts
- core/package-lock.json
- core/ts/index.ts
- domainobjs/package-lock.json
- integrationTests/package-lock.json
Simplify contracts build process.
> chore(publishing): remove bash script for empty ballot roots contract

- circuits/circom/tallyVotes.circom
- circuits/circom/trees/checkRoot.circom
- circuits/circom/trees/incrementalMerkleTree.circom
- circuits/circom/trees/incrementalQuinTree.circom
- circuits/package-lock.json
- circuits/package.json
- circuits/ts/__tests__/Ecdh.test.ts
- circuits/ts/__tests__/Hasher.test.ts
- circuits/ts/__tests__/IncrementalQuinTree.test.ts
- circuits/ts/__tests__/MessageToCommand.test.ts
- circuits/ts/__tests__/MessageValidator.test.ts
- circuits/ts/__tests__/PrivToPubKey.test.ts
- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/__tests__/QuinCheckRoot.test.ts
- circuits/ts/__tests__/Splicer.test.ts
- circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- circuits/ts/__tests__/UnpackElement.test.ts
- circuits/ts/__tests__/VerifySignature.test.ts
- circuits/ts/__tests__/utils/constants.ts
- circuits/ts/types/circom_tester.d.ts
- contracts/tests/AccQueue.test.ts
- contracts/tests/AccQueueBenchmark.test.ts
- crypto/ts/__tests__/AccQueue.test.ts
- crypto/ts/__tests__/Utils.test.ts
- domainobjs/ts/__tests__/verifyingKey.test.ts
> test(circuits): refactor and add tests for the circom circuits

- contracts/hardhat.config.ts
Ensure we can reliably understand how much gas is consumed by each function call.
> chore(contracts): add gas reporter to hardhat config

- .github/scripts/ceremony-param-tests-c-witness.sh
- cli/testScript.sh
- website/versioned_docs/version-v1.x/cli.md
- website/versioned_docs/version-v1.x/troubleshooting.md
Use maci-cli without explicit config set
N/A
Related to #1011
> chore(cli): change maci-cli script run instructions

- website/versioned_docs/version-v1.x/testing-in-detail.md
- website/versioned_docs/version-v1.x/testing.md
Fix wrong circuit param description and add disclaimers about test artifacts.
fix #1055
> docs(circuits): fix wrong circuit param description

- website/versioned_docs/version-v1.x/integrating.md
> docs(integration): clarify integraration docs

- README.md
#1068 follow-up, had trouble amending from my new equipment so I made another PR.
Sorry for not using the correct convention rules from the get go, hopefully it's good now
> docs: add licence link to README

- .github/workflows/slither.yml
Add slither github action for smart contracts checks
N/A
N/A
> chore: add slither github action

- circuits/package.json
- circuits/ts/compile.ts
- circuits/ts/genZkeys.ts
- pnpm-lock.yaml
Update circomkit to the latest version to benefit from faster zkey generation. Also add some logging into the build and zkey gen scripts to ensure failures are easier to debug.
> chore(deps): update circomkit to latest version and add console logs

- contracts/hardhat.config.ts
- contracts/tasks/deploy/index.ts
- contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
- contracts/tasks/deploy/maci/02-freeForAllSignUpGatekeeper.ts
- contracts/tasks/deploy/maci/03-verifier.ts
- contracts/tasks/deploy/maci/04-topupCredit.ts
- contracts/tasks/deploy/maci/05-poseidon.ts
- contracts/tasks/deploy/maci/06-pollFactory.ts
- contracts/tasks/deploy/maci/07-messageProcessorFactory.ts
- contracts/tasks/deploy/maci/08-tallyFactory.ts
- contracts/tasks/deploy/maci/09-subsidyFactory.ts
- contracts/tasks/deploy/maci/10-maci.ts
- contracts/tasks/helpers/ContractStorage.ts
- contracts/tasks/helpers/ContractVerifier.ts
- contracts/tasks/helpers/Deployment.ts
- contracts/tasks/helpers/constants.ts
- contracts/tasks/runner/deployFull.ts
- contracts/tasks/runner/verifyFull.ts
> docs(contracts): add documentation for deployment workflow

- cli/tests/e2e/e2e.test.ts
- contracts/contracts/Tally.sol
- contracts/tests/Tally.test.ts
Ensure we stop tallying ballots correctly, and that an event is emitted even if batchStartIndex == number of ballots
fix #1137
> fix(contracts): fix wrong tally processing check

- website/src/pages/index.tsx
There is a section describing what the maci is about. In the content of the answer, there is a single line (#L3) with word repetition. The specific line is _"This ensures the correct the correct execution of votes"_. This PR removes the word repetition and ensures clarity of the content. 
This PR resolves the raised issue #1140
> docs: fix word repetition

- circuits/circom/circuits.json
- circuits/circom/hasherSha256.circom
- circuits/circom/messageHasher.circom
- circuits/circom/messageToCommand.circom
- circuits/circom/messageValidatorNonQv.circom
- circuits/circom/poseidon/poseidonHashT3.circom
- circuits/circom/poseidon/poseidonHashT4.circom
- circuits/circom/poseidon/poseidonHashT5.circom
- circuits/circom/poseidon/poseidonHashT6.circom
- circuits/circom/processMessagesNonQv.circom
- circuits/circom/stateLeafAndBallotTransformerNonQv.circom
- circuits/circom/subsidy.circom
- circuits/circom/tallyVotesNonQv.circom
- circuits/circom/trees/checkRoot.circom
- circuits/circom/trees/incrementalQuinTree.circom
- circuits/circom/unpackElement.circom
- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/__tests__/TallyVotes.test.ts
- cli/package.json
- cli/tests/constants.ts
- cli/tests/e2e/e2e.nonQv.test.ts
- cli/ts/commands/genProofs.ts
- cli/ts/index.ts
- cli/ts/utils/interfaces.ts
- core/ts/Poll.ts
- core/ts/__tests__/Poll.test.ts
- core/ts/__tests__/e2e.test.ts
Amend all parts of the code to support both quadratic and non quadratic voting. Circuits for non quadratic voting have a slight reduction in constraints (especially processMessages). Tests added for the feature in both cli e2e, core e2e and unit, and circuits unit tests.
* `processMessagesNonQv` constraints for `10-2-1-2` -> from 342690 to 338885
* `tallyVotesNonQv` constraints for `10-1-2` -> from 117174 to 116924
related to #1145
> feat(qv): add optional flag to use quadratic voting or not in MACI

- contracts/contracts/gatekeepers/EASGatekeeper.sol
clarify EASGatekeeper description
None
> docs(contracts): clarify EASGatekeeper description

- circuits/circom/messageValidator.circom
- circuits/circom/processMessages.circom
- circuits/circom/processMessagesNonQv.circom
Remove todo messages which were missed from the previous PR (#1170)
> chore(circuits): remove todo messages

- cli/testScript.sh
- cli/tests/unit/poll.test.ts
- cli/ts/commands/index.ts
- cli/ts/commands/poll.ts
- cli/ts/commands/signup.ts
- cli/ts/index.ts
- cli/ts/sdk/index.ts
- cli/ts/utils/index.ts
- cli/ts/utils/interfaces.ts
- contracts/contracts/MACI.sol
- contracts/ts/genMaciState.ts
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/10
> feat(cli): add get poll cli command

- website/versioned_docs/version-v1.x/cli.md
- website/versioned_docs/version-v1.x/installation.md
Update cli walkthrough and installation docs.
fix #1243 #1244
> docs(docs): update installation docs and cli walkthrough

- package.json
Bump monorepo version to 1.2.0
> chore(repo): bump monorepo version

- crypto/package.json
- pnpm-lock.yaml
> chore: update zk-kit compatible packages

- contracts/tests/MACI.test.ts
Fix flaky tests for signups
N/A
N/A
> fix(contracts): use for-loop instead of async promise

- .eslintrc.js
- .github/workflows/benchmarks.yml
- .github/workflows/checks.yml
- .github/workflows/circuit-build.yml
- .github/workflows/commitlint.yml
- .github/workflows/contracts-build.yml
- .github/workflows/core-build.yml
- .github/workflows/crypto-build.yml
- .github/workflows/domainobjs-build.yml
- .github/workflows/e2e.yml
- .github/workflows/nightly-ceremony.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/reusable-e2e.yml
- .github/workflows/slither.yml
- pnpm-lock.yaml
- website/.gitignore
- website/docusaurus.config.ts
- website/src/scripts/utils.ts
Add generated docs to .gitignore
N/A
N/A
> fix(website): add typedoc folder to .gitignore and use pnpm v8 for ci

- website/versioned_docs/version-v1.2/integrating.md
- website/versioned_docs/version-v1.3_alpha/integrating.md
Regarding to discussion in PR #1363 , put details of "running commands in contracts/" in `integrating` section.
> docs: update integrating doc for v1.3

- website/src/scripts/setupTypedoc.ts
- website/versioned_docs/version-v1.3_alpha/troubleshooting.md
> docs(website): update trouble shooting doc

- cli/ts/sdk/index.ts
Add export from contracts, circuits for cli package
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/67
> feat(cli): add export from contracts, circuits for cli package

- website/blog/2024-04-10-roadmap-q2.md
Add meta description to blog post
#1370
> docs: add meta desc to roadmap post

- .github/scripts/download-zkeys-1-3.sh
add missing download script for v1.3(beta) test artifacts
> chore(download-script): add download script for 1.3 test artifacts

- CHANGELOG.md
- circuits/CHANGELOG.md
- circuits/package.json
- cli/CHANGELOG.md
- cli/package.json
- contracts/CHANGELOG.md
- contracts/package.json
- coordinator/package.json
- core/CHANGELOG.md
- core/package.json
- crypto/CHANGELOG.md
- crypto/package.json
- domainobjs/CHANGELOG.md
- domainobjs/package.json
- integrationTests/CHANGELOG.md
- integrationTests/package.json
- lerna.json
- pnpm-lock.yaml
- website/CHANGELOG.md
- website/package.json
> chore(release): publish 1.2.1

- website/versioned_docs/version-v1.3_alpha/circuits.md
- website/versioned_docs/version-v1.3_alpha/installation.md
update installation guide for circuit build
> docs: update installation guide for circuit build

- website/blog/2024-05-08-ethdam.md
Post mortem writeup for MACI's bug.
> docs(post-mortem): upload post mortem writeup

- contracts/package.json
- contracts/tasks/deploy/maci/02-gatekeepers.ts
- pnpm-lock.yaml
> fix(contract): gatekeeper deploy config skip

- coordinator/.env.example
- coordinator/README.md
- coordinator/hardhat.config.ts
- coordinator/package.json
Add basic docs for coordinator service
N/A
N/A
> docs(coordinator): add readme docs for coordinator

- coordinator/package.json
- coordinator/tests/app.test.ts
- coordinator/ts/app.controller.ts
- coordinator/ts/auth/AccountSignatureGuard.service.ts
- coordinator/ts/crypto/crypto.service.ts
- coordinator/ts/main.ts
- coordinator/ts/proof/proof.service.ts
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/58
> chore(coordinator): add logger

- cli/tests/unit/poll.test.ts
- cli/ts/commands/poll.ts
- cli/ts/utils/interfaces.ts
Fixed poll command to support merged state root
> fix(poll-command): fixed poll command to support merged state root

- cli/ts/sdk/index.ts
Export `extractVkToFile` function in `maci-cli/sdk`.
https://github.com/privacy-scaling-explorations/maci-rpgf/issues/113
> feat: export extractVkToFile function

- .github/scripts/build.sh
- .github/workflows/coordinator-deploy.yml
- circuits/ts/__tests__/Hasher.test.ts
- circuits/ts/__tests__/PrivToPubKey.test.ts
- coordinator/.env.example
- coordinator/README.md
- coordinator/tests/app.test.ts
- coordinator/ts/auth/AccountSignatureGuard.service.ts
- coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
- coordinator/ts/file/__tests__/file.service.test.ts
- coordinator/ts/main.ts
> feat(coordinator): update authorization

- contracts/deploy-config-example.json
- contracts/tasks/runner/prove.ts
Removed some parameters from the prove tasks and added them to the deploy-config
> refactor(tasks): removed params from prove task

- circuits/ts/__tests__/IncrementalQuinaryTree.test.ts
Remove only for circuits tests
N/A
N/A
> fix(circuits): remove only for circuits tests

- subgraph/package.json
Fix npm publish ci job
N/A
N/A
> fix(subgraph): add version and files for package.json

- subgraph/schemas/schema.v1.graphql
- subgraph/src/maci.ts
Remove user-polls relation for subgraph
N/A
Related https://github.com/privacy-scaling-explorations/maci-rpgf/issues/153
> fix(subgraph): remove user-polls relation

- cli/ts/commands/signup.ts
changed validation for the signup data and voice credit data
> fix(cli): changed validation for the signup data and voice credit data

- subgraph/.gitignore
- subgraph/config/optimism-sepolia.json
- subgraph/schemas/schema.v1.graphql
- subgraph/src/maci.ts
- subgraph/src/poll.ts
- subgraph/src/utils/entity.ts
Optimize subgraph schema
N/A
N/A
> feat(subgraph): optimize subgraph schema

- website/blog/2024-06-17-understanding-maci.md
Add understanding maci blogpost
> docs(blog): add understanding maci blogpost

- cli/tests/unit/signup.test.ts
> test(signup): fix flaky test

- circuits/README.md
- cli/README.md
- contracts/README.md
> docs(docs): fixed broken links

- cli/ts/index.ts
> fix(cli): fix vk commands flags

- contracts/contracts/gatekeepers/SemaphoreGatekeeper.sol
- contracts/deploy-config-example.json
- contracts/tasks/deploy/maci/02-gatekeepers.ts
- contracts/tasks/helpers/types.ts
- website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
- website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md
Add deployment steps for SemaphoreGatekeeper
> feat(contracts): add deployment code for SemaphoreGatekeeper

- website/versioned_docs/version-v1.2/contributing/contributing.md
- website/versioned_docs/version-v2.0_alpha/contributing/contributing.md
Update contributing guide with commit squashing information
N/A
N/A
> docs: update contributing guide with squash info

- website/versioned_docs/version-v2.0_alpha/security/trusted-setup.md
Add max values to the trusted setup page
> docs: add more details regarding max values

- website/versioned_docs/version-v2.0_alpha/developers-references/maci-wrapper/QuickStartGuide.md
- website/versioned_docs/version-v2.0_alpha/developers-references/maci-wrapper/_category_.json
Added MACI Wrapper Quickstarter guide in the docs.
> feat(website): added maci wrapper quickstarter in the docs

- contracts/contracts/Poll.sol
- contracts/contracts/interfaces/IMACI.sol
- contracts/contracts/interfaces/IPoll.sol
- website/versioned_docs/version-v1.2/solidity-docs/Poll.md
- website/versioned_docs/version-v1.2/solidity-docs/interfaces/IPoll.md
Minor contracts cleanup and typo fixes
N/A
> chore(contracts): optimization and typo fixes

- cli/tests/e2e/e2e.test.ts
- cli/ts/commands/index.ts
- cli/ts/commands/signup.ts
- cli/ts/sdk/index.ts
- cli/ts/utils/index.ts
- cli/ts/utils/interfaces.ts
- contracts/contracts/gatekeepers/EASGatekeeper.sol
- contracts/contracts/gatekeepers/FreeForAllSignUpGatekeeper.sol
- contracts/contracts/gatekeepers/GitcoinPassportGatekeeper.sol
- contracts/contracts/gatekeepers/HatsGatekeeperBase.sol
- contracts/contracts/gatekeepers/SemaphoreGatekeeper.sol
- contracts/contracts/gatekeepers/SignUpGatekeeper.sol
- contracts/contracts/gatekeepers/SignUpTokenGatekeeper.sol
- contracts/contracts/gatekeepers/zupass/ZupassGatekeeper.sol
Add a name trait to gatekeepers so we can distinguish on client applications
> chore: add name to gatekeepers and add sdk function

- cli/ts/commands/index.ts
- cli/ts/commands/signup.ts
change import type to import for Enum value GatekeeperTrait
> fix: do not import enum as type

- contracts/tasks/helpers/Deployment.ts
Add missing text on deployment task 
fix #1439
> chore(deployment): add missing text

- .npmrc
> fix: pnpm publish

- circuits/circom/trees/incrementalQuinaryTree.circom
- circuits/circom/utils/messageToCommand.circom
- circuits/circom/utils/verifySignature.circom
Minor optimization for circuits
N/A
> chore(circuits): optimize message to command

- .github/workflows/e2e.yml
- .github/workflows/release.yml
Remove staging emptyBallotRoots file as it does not change anymore
> fix(publish): fix publish workflow by not committing changed files

- website/blog/2024-07-30-roadmap-q3.md
> docs(blog): add q3 roadmap post

- circuits/circom/circuits.json
- circuits/circom/core/non-qv/processMessages.circom
- circuits/circom/core/qv/processMessages.circom
- circuits/circom/test/ProcessMessages_10-2-1-2_test.circom
- circuits/ts/__tests__/CeremonyParams.test.ts
- circuits/ts/__tests__/ProcessMessages.test.ts
- circuits/ts/types.ts
- cli/ts/commands/proveOnChain.ts
- contracts/contracts/MessageProcessor.sol
- contracts/tasks/helpers/Prover.ts
- contracts/ts/genMaciState.ts
- core/ts/Poll.ts
- core/ts/utils/types.ts
- website/versioned_docs/version-v2.0_alpha/core-concepts/spec.md
- website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/processMessages.md
- website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/tallyVotes.md
- website/versioned_docs/version-v2.0_alpha/quick-start/installation.md
Add coordinator public key hash public input for MP circuits
Blocked by #1725 
> fix: add coordinator public key hash public input

- apps/website/blog/2024-08-10-maci-v2.md
Add v2 blogpost 
merge first #1722
> docs(blog): add v2 blog post

- packages/contracts/default-deployed-contracts.json
- packages/contracts/tasks/deploy/maci/08-maci.ts
Fix MACI's contract failed block explorer verification
> fix: contract verification for maci

- CHANGELOG.md
- apps/subgraph/CHANGELOG.md
- apps/subgraph/package.json
- apps/website/CHANGELOG.md
- apps/website/package.json
- lerna.json
- package.json
- packages/circuits/CHANGELOG.md
- packages/circuits/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- packages/integrationTests/CHANGELOG.md
- packages/integrationTests/package.json
- pnpm-lock.yaml
> chore(release): publish 2.1.0

- packages/contracts/ts/index.ts
Add `IDeployParams` to exports for `maci-contracts`
N/A
> chore(contracts): add deploy params type

- .github/workflows/hardhat-tasks.yml
- packages/contracts/deploy-config-example.json
- packages/contracts/tasks/helpers/Prover.ts
- packages/contracts/tasks/runner/prove.ts
Use correct contract for message processor and ensure public inputs are not readonly
> fix: ensure prove task works

- packages/contracts/default-deployed-contracts.json
- packages/contracts/tasks/deploy/maci/01-constantInitialVoiceCreditProxy.ts
- packages/contracts/tasks/deploy/maci/02-gatekeepers.ts
- packages/contracts/tasks/deploy/maci/03-verifier.ts
- packages/contracts/tasks/deploy/maci/04-poseidon.ts
- packages/contracts/tasks/deploy/maci/05-pollFactory.ts
- packages/contracts/tasks/deploy/maci/06-messageProcessorFactory.ts
- packages/contracts/tasks/deploy/maci/07-tallyFactory.ts
- packages/contracts/tasks/deploy/maci/08-maci.ts
- packages/contracts/tasks/deploy/maci/09-vkRegistry.ts
Deploy to sepolia and store addresses for re-use. Also add message to console when skipping deployment of contracts (via incremental)
> chore: deploy to sepolia and store contracts

- packages/contracts/contracts/Poll.sol
> feat(contracts): make poll modifiers virtual

- packages/cli/ts/commands/poll.ts
- packages/cli/ts/utils/interfaces.ts
Get the poll mode within getPoll in sdk
> chore: get poll mode within sdk

- apps/website/blog/2024-08-29-anonymous-poll-joining.md
- apps/website/docusaurus.config.ts
PR with blog for Anonymous Poll Joining grant.
#1566
> docs(blog): anonymous poll joining

- CHANGELOG.md
- apps/subgraph/CHANGELOG.md
- apps/subgraph/package.json
- apps/website/CHANGELOG.md
- apps/website/package.json
- lerna.json
- package.json
- packages/circuits/CHANGELOG.md
- packages/circuits/package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/contracts/CHANGELOG.md
- packages/contracts/package.json
- packages/integrationTests/CHANGELOG.md
- packages/integrationTests/package.json
- pnpm-lock.yaml
> chore: publish 2.3.0

- packages/contracts/tasks/deploy/maci/08-maci.ts
- packages/contracts/tasks/helpers/types.ts
Sets the maci instance of any gatekeeper
> fix(deploy-maci): sets the maci instance of any gatekeeper

- packages/contracts/contracts/Poll.sol
Add missing virtual modifiers
N/A
> feat(contracts): add virtual modifiers for poll

- packages/contracts/contracts/Poll.sol
Add virtual modifier for Poll method `getDeployTimeAndDuration`
N/A
> feat(contracts): add virtual modifier for getDeployTimeAndDuration

- packages/contracts/ts/index.ts
Add missing exports for contracts package
N/A
Related to https://github.com/privacy-scaling-explorations/maci-platform/issues/433
> chore(contracts): add missing exports

- apps/website/versioned_docs/version-v0.x/quadratic-vote-tallying-circuit.md
- apps/website/versioned_docs/version-v2.x/use-cases/public-goods-funding/quadratic-funding/what-is-quadratic-funding.md
The previous address has expired, use the latest one
> chore: update vitalik blog link

- apps/website/versioned_docs/version-v1.2/typedoc/core/index.md
- packages/core/README.md
The previous link has expired and has been replaced with the latest address.
> chore: fix 404 status URL

- .github/workflows/nightly-mac.yml
Add nightly workflow for MACI
fix #839
> feat: add nightly workflow for mac

- apps/website/blog/2024-12-01-maci-getting-started.md
- packages/contracts/.env.example
Getting started with the MACI tutorial as a blog post.
> docs(blog): getting started blog post

- apps/website/versioned_docs/version-v2.x/guides/frontend.md
Added stable version to frontend guide
> docs(frontend-guide): added version

- packages/contracts/contracts/Poll.sol
Use view modifier for verifying poll proof and getting circuit inputs
N/A
Closes #1838
> chore: use view modifier for verifying poll proof

- apps/website/versioned_docs/version-v2.x/guides/subgraph.md
Updated subgraph guide with instructions for Alchemy
> docs(subgraph-docs): added alchemy to subgraph docs

- packages/contracts/tasks/deploy/poll/01-poll.ts
Minor fix for poll contract verification 
N/A
N/A
> fix(contracts): use correct param for poll contract verification

- apps/website/versioned_docs/version-v2.x/resources.md
Added link to article about how to setup and run MACI aimed for developers.
None
None
> docs(documentation): added getting started with maci article to docs

- apps/website/src/content/projects.json
> docs: add PGA to project list

- .github/pull_request_template.md
> chore: updated pr template

- .github/pull_request_template.md
Updated small typo on PR template
> chore: fixed typo on pr template

- apps/website/versioned_docs/version-v2.x/case-studies.md
updated titles and added Cryptoversidad and Devcon Sea
> [!IMPORTANT]
> docs(case-studies): updated case studies

- apps/website/blog/2024-11-20-maci-platform.md
> docs: replace space in slug with dash

- apps/website/versioned_docs/version-v2.x/case-studies.md
Added ETH TGU, ETH MX and changed order of case studies
> [!IMPORTANT]
> docs(case-studies): added eth tgu and eth mx

- apps/relayer/jest.config.json
- apps/relayer/package.json
- apps/relayer/tests/deploy.ts
- apps/relayer/tests/messageBatches.test.ts
- apps/relayer/tests/messages.test.ts
- apps/relayer/ts/jest/setup.ts
- apps/relayer/ts/messageBatch/__tests__/messageBatch.controller.test.ts
- apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
- apps/relayer/ts/messageBatch/__tests__/utils.ts
- apps/relayer/ts/messageBatch/__tests__/validation.test.ts
- apps/relayer/ts/messageBatch/messageBatch.controller.ts
- apps/relayer/ts/messageBatch/messageBatch.dto.ts
- apps/relayer/ts/messageBatch/messageBatch.module.ts
- apps/relayer/ts/messageBatch/messageBatch.repository.ts
- apps/relayer/ts/messageBatch/messageBatch.service.ts
- apps/relayer/ts/messageBatch/validation.ts
This is a part of happy offchain path
> [!IMPORTANT]
> feat(relayer): fetch message batches

- packages/contracts/contracts/Poll.sol
- packages/contracts/contracts/interfaces/IMACI.sol
- packages/contracts/contracts/interfaces/IPoll.sol
Update contracts interfaces
> [!IMPORTANT]
> chore: update contracts interfaces

- apps/relayer/tests/deploy.ts
- apps/relayer/tests/onchain.test.ts
- apps/relayer/ts/ipfs/__tests__/ipfs.service.test.ts
- apps/relayer/ts/ipfs/ipfs.service.ts
- apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
- apps/relayer/ts/messageBatch/messageBatch.service.ts
- packages/sdk/ts/index.ts
- packages/sdk/ts/poll/index.ts
Add checks for onchain publishing with cron
This is a part of happy offchain path
> [!IMPORTANT]
> test(relayer): add checks for onchain publishing

- packages/cli/ts/index.ts
- packages/cli/ts/utils/interfaces.ts
- packages/contracts/contracts/Poll.sol
- packages/sdk/package.json
- packages/sdk/ts/user/index.ts
- packages/sdk/ts/user/types.ts
- packages/sdk/ts/user/user.ts
- packages/sdk/ts/user/utils.ts
- packages/sdk/ts/utils/index.ts
- packages/sdk/ts/utils/proofs.ts
- pnpm-lock.yaml
Refactor join poll SDK commands
re #1981 
> [!IMPORTANT]
> refactor: join poll sdk

- apps/relayer/tests/deploy.ts
- packages/cli/tests/ceremony-params/ceremonyParams.test.ts
- packages/cli/tests/e2e/e2e.nonQv.test.ts
- packages/cli/tests/e2e/e2e.test.ts
- packages/cli/tests/e2e/keyChange.test.ts
- packages/cli/tests/unit/joinPoll.test.ts
- packages/cli/tests/unit/poll.test.ts
- packages/cli/tests/unit/publish.test.ts
- packages/cli/tests/unit/signup.test.ts
- packages/cli/ts/commands/index.ts
- packages/cli/ts/commands/setVerifyingKeys.ts
- packages/cli/ts/index.ts
- packages/integrationTests/ts/__tests__/integration.test.ts
- packages/sdk/ts/keys/index.ts
- packages/sdk/ts/keys/types.ts
- packages/sdk/ts/keys/verifyingKeys.ts
refactor set verifying keys sdk command
re #1981 
> [!IMPORTANT]
> refactor: setVerifyingKeys

- .gitignore
- packages/cli/tests/ceremony-params/ceremonyParams.test.ts
- packages/cli/tests/e2e/e2e.nonQv.test.ts
- packages/cli/tests/e2e/e2e.test.ts
- packages/cli/tests/e2e/keyChange.test.ts
- packages/cli/ts/commands/genProofs.ts
- packages/cli/ts/commands/index.ts
- packages/cli/ts/index.ts
- packages/contracts/tasks/helpers/ProofGenerator.ts
- packages/contracts/tasks/runner/prove.ts
- packages/integrationTests/ts/__tests__/integration.test.ts
- packages/sdk/ts/index.ts
- packages/sdk/ts/proofs/genProofs.ts
- packages/sdk/ts/proofs/index.ts
- packages/sdk/ts/proofs/types.ts
- packages/sdk/ts/utils/files.ts
- packages/sdk/ts/utils/formatting.ts
Refactor genProofs command
re #1981 
> [!IMPORTANT]
> refactor: gen proofs

- packages/sdk/ts/vote/invalidate.ts
- packages/sdk/ts/vote/types.ts
Add a function to invalidate previous votes
> [!IMPORTANT]
> feat: add invalidate votes function

- README.md
- apps/coordinator/package.json
- apps/relayer/package.json
- packages/circuits/package.json
- packages/cli/package.json
- packages/sdk/package.json
- packages/testing/package.json
- pnpm-lock.yaml
Update README to include all packages
> [!IMPORTANT]
> docs: update the readme

- packages/contracts/contracts/gatekeepers/zupass/ZupassChecker.sol
- packages/contracts/contracts/gatekeepers/zupass/ZupassCheckerFactory.sol
- packages/contracts/contracts/gatekeepers/zupass/ZupassGatekeeper.sol
- packages/contracts/contracts/gatekeepers/zupass/ZupassGatekeeperFactory.sol
- packages/contracts/tasks/deploy/maci/01-gatekeepers.ts
- packages/contracts/tasks/deploy/poll/02-gatekeepers.ts
- packages/contracts/tests/gatekeepers/ZupassGatekeeper.test.ts
- packages/contracts/ts/deploy.ts
- packages/sdk/ts/maci/gatekeeper.ts
This is a part of excubiae integration
Related to #1926
Blocked by #2231 
> [!IMPORTANT]
> feat(contracts): add zupass gatekeeper checker

- packages/contracts/contracts/gatekeepers/anonAadhaar/AnonAadhaarChecker.sol
- packages/contracts/contracts/gatekeepers/eas/EASChecker.sol
- packages/contracts/contracts/gatekeepers/freeForAll/FreeForAllChecker.sol
- packages/contracts/contracts/gatekeepers/gitcoin/GitcoinPassportChecker.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofChecker.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofCheckerFactory.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofGatekeeper.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofGatekeeperFactory.sol
- packages/contracts/contracts/gatekeepers/zupass/ZupassChecker.sol
- packages/contracts/tasks/deploy/maci/01-gatekeepers.ts
- packages/contracts/tasks/deploy/poll/02-gatekeepers.ts
- packages/contracts/tests/gatekeepers/MerkleProofGatekeeper.test.ts
- packages/contracts/ts/deploy.ts
- packages/sdk/ts/maci/gatekeeper.ts
This is a part of excubiae integration
Related to #1926
Blocked by #2266
> [!IMPORTANT]
> feat(contracts): add merkle proof gatekeeper checker 

- apps/website/blog/2025-03-21-roadmap-2025.md
Add 2025 roadmap blogpost
> [!IMPORTANT]
> docs: roadmap 2025 blogpost

- packages/contracts/contracts/trees/LeanIMT.sol
- packages/contracts/tests/MACI.test.ts
- packages/contracts/tests/gatekeepers/GitcoinPassportGatekeeper.test.ts
- packages/testing/ts/__tests__/e2e.test.ts
Prevent duplicate MACI key signups
> [!IMPORTANT]
> feat: prevent duplicate maci key signup

- packages/contracts/contracts/gatekeepers/anonAadhaar/AnonAadhaarChecker.sol
- packages/contracts/contracts/gatekeepers/eas/EASChecker.sol
- packages/contracts/contracts/gatekeepers/freeForAll/FreeForAllChecker.sol
- packages/contracts/contracts/gatekeepers/gitcoin/GitcoinPassportChecker.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofChecker.sol
- packages/contracts/contracts/gatekeepers/merkle/MerkleProofGatekeeper.sol
- packages/contracts/contracts/gatekeepers/token/SignUpTokenChecker.sol
- packages/contracts/contracts/gatekeepers/token/SignUpTokenCheckerFactory.sol
- packages/contracts/contracts/gatekeepers/token/SignUpTokenGatekeeper.sol
- packages/contracts/contracts/gatekeepers/token/SignUpTokenGatekeeperFactory.sol
- packages/contracts/contracts/gatekeepers/zupass/ZupassChecker.sol
- packages/contracts/tests/gatekeepers/SignUpGatekeeper.test.ts
- packages/contracts/ts/deploy.ts
This is a part of excubiae integration
Related to #1926
Blocked by #2270 
> [!IMPORTANT]
> feat(contracts): add signup token gatekeeper checker

- packages/sdk/ts/user/index.ts
- packages/sdk/ts/user/types.ts
- packages/sdk/ts/user/user.ts
Check if a user is registered using their public key 
> [!IMPORTANT]
> feat: check if a user is registered

- packages/sdk/package.json
- packages/sdk/ts/browser/index.ts
Add extra export without deploy functions for more compatibility 
> [!IMPORTANT]
> fix: add export without deploy functions

- .prettierignore
- apps/coordinator/package.json
- apps/relayer/package.json
- apps/website/package.json
Make all packages public as free org cannot publish private ones
> [!IMPORTANT]
> chore: remove private packages

- apps/coordinator/package.json
- apps/relayer/package.json
- apps/subgraph/package.json
- apps/website/package.json
- packages/circuits/package.json
- packages/cli/package.json
- packages/contracts/package.json
- packages/core/package.json
- packages/crypto/README.md
- packages/crypto/package.json
- packages/domainobjs/package.json
- packages/sdk/package.json
- packages/testing/package.json
- pnpm-lock.yaml
add publishConfig directive to package.json 
> [!IMPORTANT]
> chore: add publishConfig

- packages/contracts/tasks/runner/benchmarks.ts
Fix error in publishMessages benchmark script
> [!IMPORTANT]
> fix(contracts): publish benchmark script

- packages/cli/ts/index.ts
- packages/contracts/tasks/deploy/maci/01-gatekeepers.ts
- packages/contracts/tasks/deploy/poll/02-gatekeepers.ts
- packages/contracts/tests/Poll.test.ts
- packages/contracts/tests/Tally.test.ts
- packages/contracts/tests/policies/AnonAadhaarPolicy.test.ts
- packages/contracts/tests/policies/EASPolicy.test.ts
- packages/contracts/tests/policies/GitcoinPassportPolicy.test.ts
- packages/contracts/tests/policies/HatsPolicy.test.ts
- packages/contracts/tests/policies/MerkleProofPolicy.test.ts
- packages/contracts/tests/policies/SemaphorePolicy.test.ts
- packages/contracts/tests/policies/SignUpPolicy.test.ts
- packages/contracts/tests/policies/Zupass.test.ts
- packages/contracts/tests/utils.ts
- packages/contracts/ts/deploy.ts
- packages/contracts/ts/index.ts
- packages/contracts/ts/types.ts
- packages/sdk/ts/deploy/poll.ts
- packages/sdk/ts/deploy/types.ts
- packages/testing/ts/__tests__/e2e.nonQv.test.ts
- packages/testing/ts/__tests__/e2e.test.ts
- packages/testing/ts/__tests__/integration.test.ts
- packages/testing/ts/__tests__/keyChange.test.ts
- packages/testing/ts/__tests__/unit/joinPoll.test.ts
- packages/testing/ts/__tests__/unit/poll.test.ts
- packages/testing/ts/__tests__/unit/publish.test.ts
- packages/testing/ts/__tests__/unit/signup.test.ts
- packages/testing/ts/testingClass.ts
N/A
Closes #2347 
> [!IMPORTANT]
> feat(contracts): reuse policy proxies factories for deployment

- apps/coordinator/ts/deployer/deployer.service.ts
- apps/coordinator/ts/deployer/types.ts
- packages/contracts/contracts/mocks/Mocker.sol
- packages/contracts/deploy-config-example.json
- packages/contracts/package.json
- packages/contracts/tasks/deploy/maci/01-gatekeepers.ts
- packages/contracts/tasks/deploy/poll/02-gatekeepers.ts
- packages/contracts/tasks/helpers/constants.ts
- packages/contracts/tasks/helpers/types.ts
- packages/contracts/tests/policies/ERC20Votes.test.ts
- packages/contracts/ts/deploy.ts
Integrate Excubiae's ERC20Votes policy 
> [!IMPORTANT]
> feat: add erc20Votes policy deployment

- packages/sdk/ts/browser/joinPoll.ts
Ensure we import only the needed functions to be browser compatible 
> [!IMPORTANT]
> fix(sdk): use full path import for sdk users functions

- packages/sdk/ts/trees/stateTree.ts
Change import from console to assert 
> [!IMPORTANT]
> chore: change assert import

- packages/contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxyFactory.sol
- packages/contracts/contracts/initialVoiceCreditProxy/ERC20VotesInitialVoiceCreditProxyFactory.sol
Return the address of the freshly deployed clone
> [!IMPORTANT]
> feat(contracts): return voice credit proxy clone address on deploy

- apps/coordinator/.env.example
- apps/coordinator/hardhat.config.cjs
- apps/coordinator/package.json
- apps/coordinator/tests/e2e.aa.test.ts
- apps/coordinator/tests/e2e.deploy.test.ts
- apps/coordinator/ts/common/__tests__/common.test.ts
- apps/coordinator/ts/common/accountAbstraction.ts
- apps/coordinator/ts/common/chain.ts
- apps/coordinator/ts/common/index.ts
- apps/coordinator/ts/deployer/__tests__/utils.ts
- apps/coordinator/ts/deployer/deployer.service.ts
- apps/coordinator/ts/deployer/dto.ts
- apps/coordinator/ts/deployer/types.ts
- apps/coordinator/ts/proof/dto.ts
- apps/coordinator/ts/proof/proof.service.ts
- apps/coordinator/ts/proof/types.ts
Add option to interact with chain using local signer rather than smart account
> [!IMPORTANT]
> feat: deployer service with local signer

- LICENSE
- apps/website/src/pages/roadmap.md
- packages/circuits/circom/coordinator/non-qv/processMessages.circom
Update roadmap entry 
> [!IMPORTANT]
> docs: update roadmap entry

- packages/sdk/package.json
Sort out the types for browser SDK export
> [!IMPORTANT]
> chore(sdk): sort out types for browser export

- packages/contracts/package.json
- packages/contracts/tests/ipfs.test.ts
- pnpm-lock.yaml
Don't rely on ipfs data in tests
N/A
N/A
> [!IMPORTANT]
> fix(contracts): add sinon for mocking fetch

- apps/website/versioned_docs/version-v3.x/core-concepts/poll-types.md
- apps/website/versioned_docs/version-v3.x/core-concepts/polls.md
- apps/website/versioned_docs/version-v3.x/guides/integrating.md
- apps/website/versioned_docs/version-v3.x/quick-start.md
- apps/website/versioned_docs/version-v3.x/supported-networks/deployed-contracts.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/MACI.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/MessageProcessor.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/Params.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/Poll.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/PollFactory.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/Tally.md
- apps/website/versioned_docs/version-v3.x/technical-references/smart-contracts/VkRegistry.md
- apps/website/versioned_docs/version-v3.x/technical-references/zk-snark-circuits/zk-snark-circuits.md
Came across some broken links when checking out the docs so fixed them.
I assume there are more broken links, but just fixed the ones I came across. Let me know if you want me to do a more thorough check
> [!IMPORTANT]
> docs: fix broken links

- README.md
Fix broken link
fix #2444 
> [!IMPORTANT]
> fix(docs): installation link

- apps/website/docusaurus.config.ts
fix edit path in docusaurus config
fix #2445 
> [!IMPORTANT]
> fix(docs): fix docusaurus edit path

- packages/sdk/ts/user/signup.ts
The SDK function `getSignedupUserData ` was initially parsing the `SignUpEvent`'s in the MACI contract. This is not efficient if the sign up happened a while back (that is why the function even had a startBlock parameter).
I copied the logic from `hasUserSignedUp` (function below) and modify it a bit to return the stateIndex as well. 
> [!IMPORTANT]
> refactor(user): get signUp data from contract call instead of events

- .github/scripts/downloadZkeys.ts
* Add a percentage log to the output of `downloadZkeys.ts` 
* Do not output any log if `response.headers["content-length"]` is null or undefined
* `\r`: goes to beginning of current line, used to overwrite same line instead of printing a new message on a new line
* `\n`: goes to new line after download has completed
Thought it would be helpful to display a download percentage to devs downloading zkeys. Let me know if you think it is unnecessary. Tested on my machine and works accurately. Was concerned that `chunk.length` would not divide into `response.headers["content-length"]` accurately but it appears to. Added screenshots at the bottom to show what the output looks like.
n/a
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless …
> feat: add percentage log to zkeys download

- packages/contracts/.env.example
- packages/contracts/hardhat.config.ts
- packages/contracts/package.json
- packages/contracts/tests/MACI.test.ts
- packages/contracts/tests/Poll.test.ts
- packages/contracts/tests/Tally.test.ts
- pnpm-lock.yaml
All the tests (contracts, integration, e2e) and deployments are passed for scroll, linea and zksync forks.
Related to #1936 
> [!IMPORTANT]
> test: zkevm fork running support

- packages/contracts/contracts/Tally.sol
- packages/sdk/ts/tally/index.ts
- packages/sdk/ts/tally/results.ts
- packages/sdk/ts/tally/types.ts
Ensure it does not throw when results are not set by returning the set flag too 
> [!IMPORTANT]
> feat(sdk): add set flag to tally result

- apps/coordinator/Dockerfile
- apps/coordinator/README.md
- apps/coordinator/docker-compose.yml
- apps/coordinator/tests/e2e.deploy.test.ts
- apps/coordinator/ts/app.module.ts
- apps/coordinator/ts/common/chain.ts
- apps/coordinator/ts/file/file.service.ts
- apps/coordinator/ts/health/__tests__/health.controller.test.ts
- apps/coordinator/ts/health/__tests__/health.service.test.ts
- apps/coordinator/ts/health/health.controller.ts
- apps/coordinator/ts/health/health.module.ts
- apps/coordinator/ts/health/health.service.ts
- apps/coordinator/ts/health/types.ts
1. Dockerize coordinator service so you can easily run it using the README.md instructions
2. Added a health module to check if rapidsnark is available, zkeys are downloaded and the coordinator wallet has funds
> [!IMPORTANT]
> feat: dockerize coordinator

- .github/workflows/coordinator-docker.yml
- .github/workflows/coordinator.yml
- apps/coordinator/.env.example
- apps/coordinator/Dockerfile
- apps/coordinator/docker-compose.yml
- apps/coordinator/package.json
- apps/coordinator/tests/e2e.redis.test.ts
- apps/coordinator/ts/app.module.ts
- apps/coordinator/ts/health/__tests__/health.controller.test.ts
- apps/coordinator/ts/health/__tests__/health.service.test.ts
- apps/coordinator/ts/health/health.module.ts
- apps/coordinator/ts/health/health.service.ts
- apps/coordinator/ts/health/types.ts
- apps/coordinator/ts/redis/__tests__/redis.service.test.ts
- apps/coordinator/ts/redis/redis.module.ts
- apps/coordinator/ts/redis/redis.service.ts
- apps/coordinator/ts/redis/types.ts
- apps/coordinator/ts/redis/utils.ts
- pnpm-lock.yaml
Added the Redis module for a persistent database, some utility functions and types. Also created some tests. It is a sub PR of #2642 
I decided to divide that PR in:
1. ✅  Redis module
2. Scheduler module
3. Finalize function in proof module (merge, generate and submit)
4. Get deployment poll
> [!IMPORTANT]
> feat(coordinator): add redis module

- .github/workflows/coordinator.yml
- .github/workflows/relayer-build.yml
- .github/workflows/reusable-e2e.yml
Return get-changed-files check back
N/A
N/A
> [!IMPORTANT]
> chore: enable get-changed-files for workflows

- apps/coordinator/.env.example
- apps/coordinator/ts/proof/proof.module.ts
- apps/coordinator/ts/scheduler/__tests__/scheduler.service.test.ts
- apps/coordinator/ts/scheduler/scheduler.module.ts
- apps/coordinator/ts/scheduler/scheduler.service.ts
- apps/coordinator/ts/scheduler/types.ts
Implement finalize function in scheduler to call in the setTimeout.
> [!IMPORTANT]
> feat(coordinator): finalize function in scheduler

- .github/workflows/nightly-mac.yml
- .github/workflows/nightly.yml
- apps/relayer/tests/constants.ts
Run tests for all the packages using the same workflow with key generation.
This is the last PR, nightly workflows are passing. 
Need to add team notification for failed workflows.
N/A
> [!IMPORTANT]
> fix: optimize nightly workflows

- packages/sdk/ts/user/utils.ts
In the Aragon MACI Plugin we were having some issues with Rabby and Rainbow wallet. The main problem is that wallets use their own RPC endpoint when executing write functions. When you request a transaction, the wallet is the JSON‑RPC client and will use its own node(s) to send/broadcast. That’s by design in EIP‑1193.
The issue was that these RPC endpoints had some rate limits lower than Metamask and we were getting errors related to "the amount of blocks to fetch is not available in the free tier" or similar.
I fixed some things in the UI repo (https://github.com/privacy-scaling-explorations/maci-aragon-osx-gov-app/pull/65) but I was able to map down the error to these two functions: `generateMaciStateTreeWithEndKey` and `generateMaciStateTree`. So I decided to move the `fromBlock` logic …
> fix(sdk): start block before fetching events

- packages/testing/ts/__tests__/stress/stress.full.test.ts
Fix nightly tests
> [!IMPORTANT]
> fix(testing): set specific mode in verifying keys
