privacy-ethereum/maci

contracts/sol/MACI.sol
contracts/ts/deploy.ts

This simplifies the deployment process.

Deploy the snark verifier contracts in the MACI contract constructor

---

circuits/package.json
circuits/ts/__tests__/BatchUpdateStateTree.test.ts
circuits/ts/__tests__/Decrypt.test.ts
circuits/ts/__tests__/Ecdh.test.ts
circuits/ts/__tests__/PublicKey.test.ts
circuits/ts/__tests__/UpdateStateTree.test.ts
circuits/ts/__tests__/VerifySignature.test.ts
contracts/ts/__tests__/Maci.test.ts
crypto/ts/__tests__/Crypto.test.ts
crypto/ts/index.ts
domainobjs/ts/__tests__/DomainObjs.test.ts
domainobjs/ts/index.ts

This PR:
1. Encapsulates `maci-crypto`'s `Keypair`, `PubKey`, and `PrivKey` in domain objects, so that we have `asCircuitInputs()` and `asContractParams()` functions available.
2. Renames `KeyPair` to `Keypair`

[domainobjs] Create a Keypair, PrivKey, and PubKey domain object so it is easier to pass keys to contracts and circuits

---

contracts/sol/DomainObjs.sol
contracts/sol/Hasher.sol
contracts/sol/MACI.sol
contracts/sol/MerkleTree.sol
contracts/ts/__tests__/Hasher.test.ts

1. Renames `Hasher.hashMulti` to `Hasher.hash` with a default key 0 so as to match `maci-crypto`'s hash() function
2. Renames `Hasher.hashPair` to `hashLeftRight` for consistency with `maci-crypto`

renamed hashPair to hashLeftRight and hashMulti to hash

---

circuits/circom/test/verifySignature_test.circom
circuits/circom/updateStateTree.circom
circuits/circom/verify_signature.circom

Fix #99 
The number of inputs to VerifySignature is now a constant. 
- No change to the number of constrains
```
circuits (master)*$ npx snarkjs info -c build/qvtCircuit.json 
circuits (master)*$ npx snarkjs info -c build/batchUstCircuit.json 
```

make number of inputs to VerifySignature a constant

---

contracts/package.json
contracts/scripts/runTestsInCircleCi.sh
contracts/sol/MACI.sol
contracts/sol/VerifyTally.sol
contracts/ts/__tests__/BatchProcessMessageAndQuadVoteTally.test.ts
contracts/ts/__tests__/VerifyTally.test.ts

This PR introduces a new contract function `MACI.verifyTallyResult()` which any contract can call to prove that they know the value of a vote tally leaf, or a batch of vote tally leaves.
Refer to https://github.com/appliedzkp/maci/issues/108 and https://github.com/appliedzkp/maci/issues/91 for more information.
The gist of it is that this function accepts a Merkle proof and the vote tally salt, recomputes the result commitment, and checks whether it matches the result commitment stored on-chain.
To prove that one knows the value of a batch of vote tally leaves, do the same but the Merkle proof should be a path to the intermediate node. e.g. I can prove that I know leaves 5-9 using a Merkle proof to intermediate node 1.
See the new unit tests in …

On-chain tally verification

---

circuits/circom/trees/incrementalQuinTree.circom

The `QuinGeneratePathIndices` circuit didn't have a range proof after each `out[i] <-- m % BASE;`. It only checked if `out[i] < BASE` and that the total sum matches `in`.
Just to be safe, this PR adds another range proof for each `out` signal.

Updated QuinGeneratePathIndices to strengthen its range proof

---

contracts/sol/DomainObjs.sol
contracts/sol/MACIParameters.sol
contracts/sol/MACIPubKey.sol
contracts/sol/MACISharedObjs.sol

This is very similar to one of my previous PRs, #114. Our contract needs access to the `Message` struct, so I'm moving it along with `PubKey` to a new lightweight abstract contract called `MACISharedObjs`. (Maybe it was the initial purpose of `DomainObjs.sol` contract?)

Move PubKey and Message structs to MACISharedObjs contract

---

contracts/sol/VerifyTally.sol
contracts/ts/__tests__/VerifyTally.test.ts

Thanks @NIC619 for spotting this bug!
This PR fixes the way the on-chain tally verification function computes the index per tree level.

Fixed incorrect Merkle proof verification logic in VerifyTally.computeMerkleRootFromPath

---

contracts/sol/MACI.sol

This is an important security check that was inadvertently left out of `proveTallyBatch()`.

In proveTallyBatch(), range-check each public signal input

---

cli/ts/utils.ts
contracts/scripts/runTestsInCircleCi.sh
contracts/sol/MACI.sol
contracts/ts/__tests__/PublishMessage.test.ts
contracts/ts/__tests__/SignUp.test.ts

Changed `SignUp` and `PublishMessage` events to enable decoding of public keys and messages.
All arguments are now non-indexed, with the exception of `_indexedUserPubKey` and `_indexedEncPubKey` as it may be useful to filter events by user's public key. 
Resolves #146

Make it possible to decode event arguments of complex types

---

contracts/ts/__tests__/BatchProcessMessageAndQuadVoteTally.test.ts
contracts/ts/__tests__/PublishMessage.test.ts
contracts/ts/__tests__/SignUp.test.ts
contracts/ts/index.ts

This prevents a downstream error with importing `timeTravel` from Etherlime.

Moved timeTravel import to individual test files

---

contracts/sol/MACI.sol

There are no `onlyOwner` methods in MACI contract, so I propose to remove `Ownable` from the list of base classes. That would save ~800 bytes in contract size.

Don't inherit from Ownable

---

contracts/sol/MACI.sol
contracts/ts/deploy.ts

@xuhcc found a bug (#155) where an vote with too many credits prevents vote processing as the `UpdateStateTree` circuit only supports a maximum of `2^32` voice credits. 
This PR enforces this limit in the `MACI.signUp()` contract function.

Enforce the voice credit limit in the MACI contract (2 ^ 32)

---

cli/package.json
cli/ts/index.ts

So it could be used as `npm run maci-cli <args>`

Set command name for MACI CLI

---

cli/ts/index.ts
cli/ts/process.ts
cli/ts/tally.ts
cli/tsconfig.json
integrationTests/ts/__tests__/utils.ts

Exporting `processMessages` and `tally` functions from `maci-cli` module to simplify integrations.

Export 'process' and 'tally' commands from maci-cli module

---

contracts/package-lock.json
contracts/package.json
contracts/scripts/compileSol.sh
contracts/sol/IncrementalMerkleTree.sol
contracts/sol/IncrementalQuinTree.sol
contracts/sol/SignUpToken.sol
contracts/ts/deploy.ts

This prevents import errors when yarn package manager is used:
```
File maci-contracts/node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol, imported from maci-contracts/sol/IncrementalQuinTree.sol, not found.
```
I also switched to `@openzeppelin/contracts` package as recommended at https://github.com/OpenZeppelin/openzeppelin-contracts
Resolves #172

Fix OZ import paths in solidity files

---

contracts/package.json

To help package managers resolve it correctly.

Make ethers a dependency in maci-contracts package

---

cli/ts/process.ts
cli/ts/utils.ts
contracts/sol/MACI.sol
contracts/ts/__tests__/BatchProcessMessageAndQuadVoteTally.test.ts

There is a bug where the contract only updates a copy of the state root when `publishMessage` is first called. This PR fixes this by updating that copy of the state root every time we call `signUp`.

Fix the postSignUpStateRoot bug

---

crypto/ts/__tests__/Crypto.test.ts
crypto/ts/index.ts

In `hash5`, `elements` is passed to `poseidonT6` instead of `elementsPadded`, which is the one ought to be used.

Crypto: fix `hash5`

---

.circleci/config.yml.deprecated
.gitignore
circuits/scripts/buildBatchUpdateStateTreeSnark.sh
circuits/scripts/buildQuadVoteTallySnark.sh
circuits/scripts/buildSnarksSmall.sh
circuits/ts/index.ts
config/prod-small.yaml
config/test.yaml

- Added config parameter `snarkParamsPath` which should resolve #197.
- Changed default directory where snark build artifacts are collected to `circuits/params`, so now they are stored separately from JS files (`circuits/build`).

Add snarkParamsPath config parameter

---

circuits/ts/index.ts
config/prod-small.yaml
config/test.yaml

I get this error with `maci-circuits 0.5.6`:
```
Error: ENOENT: no such file or directory, open `./project-dir/circuits/params/1612548070018.input.json'
```
The packaged script treats `snarkParamsPath` as relative to current working directory but it must treat it as relative to script itself. This patch should fix it.

Fix resolution of relative snark params path

---

circuits/circom/hasherPoseidon.circom
circuits/circom/messageHasher.circom
circuits/circom/processMessages.circom
circuits/circom/test/hasher10_test.circom
circuits/circom/trees/incrementalQuinTree.circom
circuits/circom/unpackElement.circom
circuits/ts/__tests__/Hasher.test.ts
contracts/contracts/Poll.sol
crypto/package-lock.json
crypto/ts/__tests__/Crypto.test.ts
crypto/ts/index.ts
domainobjs/package-lock.json
domainobjs/ts/index.ts

1. I initially thought that it was a good tradeoff to use SHA256 to hash messages so users can save gas. I came to realise that this would make it difficult for projects like clrfund to increase the message batch size for the processing circuit, as the circuit would require a lot more memory to compile.
2. The UnpackElement circuit used the right-shift `<<` operator to unpack an input value into multiple 50-bit outputs. I used a constraint to check that the outputs were correct but closer inspection by @han0110 revealed that there was actually no constraint created in the compiled circuit. As such, I've modified this circuit to use `Num2Bits_strict` to convert the input to bits, and then `n` `Bits2Num(50)` circuits to convert each 50-bit chunk to the desired output. The new circuit …

Use Poseidon instead of SHA256 to hash messages + fix the UnpackElement circuit

---

circuits/circom/hasherPoseidon.circom
circuits/circom/messageHasher.circom
circuits/circom/processMessages.circom
circuits/circom/test/hasher10_test.circom
circuits/circom/trees/incrementalQuinTree.circom
circuits/circom/unpackElement.circom
circuits/ts/__tests__/Hasher.test.ts
cli/README.md
contracts/contracts/Poll.sol
crypto/package-lock.json
crypto/ts/__tests__/Crypto.test.ts
crypto/ts/index.ts
domainobjs/package-lock.json
domainobjs/ts/index.ts

Previously, `bigInt2Buffer()` converted the hexadecimal representation of a BigInt into a Buffer, but did so incorrectly.
It did this:
```js
Buffer.from(BigInt(16).toString())
<Buffer 31 36>
```
However the following is correct:
```js
Buffer.from(BigInt(16).toString(), 'hex')
<Buffer 16>
```
The functions `genPubKey()`, `genEcdhSharedKey()`, `formatPrivKeyForBabyJub()`, and `sign()` are affected. Effectively, only half the entropy of the private key is used to generate the public key. Since the snark field size is 253 bits, the public key was generated with only 126 bits.

Fix BigInt to Buffer conversion function

---

integrationTests/integrations.yml
integrationTests/ts/__tests__/suites.ts
integrationTests/ts/__tests__/suites/suite2_bribe.json
integrationTests/ts/__tests__/utils.ts

When specifying which users will execute a bribe, the index is used to determine what the voteOptionIndex for every message

bribes integration tests

---

contracts/scripts/compileSol.sh

If a `.sol` file being compiled lives in a directory path which contains a symlink component, then the `--allowed-paths` option of `solc` only works when the symlinks are fully resolved.  So use `pwd -P` to obtain the absolute paths instead of just `pwd`.

Fix .sol compilation to work in directories which are symlinks

---

README.md

The existing instructions did not work, because they instructed the user to start their own Ganache instance, which would then conflict with the ones started by the scripts.  So clarify this, and also explain how to run individual tests one by one, which is what the `README` already recommended anyway to prevent incorrect nonce errors.

Clarify how to run tests

---

circuits/circom/tallyVotes.circom

If it's the first batch ensure zero tally commitment

---

Dockerfile

Run ```docker build -t maci . ```
To provide some context on why we want this structure for each of the submodules, when we implement github actions for different parts of the code base we can stop the build process to specific tagged intermediate images see https://docs.docker.com/develop/develop-images/multistage-build/
Essentially this will allow us to copy over cached artifacts to different images that need to be rebuilt to test new code changes

Add dockerfile as multibuild job

---

contracts/contracts/Poll.sol
contracts/contracts/trees/AccQueue.sol

Since we no longer separate commitments for voice options, this generates the commitment for the state tree. There are additional view functions to get the message leaf but this causes and exceeded contract size for mainnet. 
Not sure if this is a problem since deploying on xDai/L2 would be strongly recommended

Add view functions to caculate state commitment

---

contracts/contracts/Poll.sol

In maci/contracts/contracts/Poll.sol,
since the type of `treeArity` is `uint8`,
```
uint8 treeArity = 5;   // line 63
```
in 
```
require(   // line 73
_maxValues.maxMessages <= treeArity ** _treeDepths.messageTreeDepth &&
...
```
`treeArity ** _treeDepths.messageTreeDepth` seems to overflow when `_treeDepths.messageTreeDepth` is greater than `3`, i.e. `5^3 = 125` but `5^4 = 625` which is greater than `256`, and that makes the require statement fail.
The type of `treeArity` should be a type that can store larger values without overflow.

use uint16 for treeArity in PollFactory.deploy

---

cli/testMultiplePoll.sh
cli/ts/genProofs.ts
cli/ts/mergeMessages.ts
cli/ts/mergeSignups.ts
contracts/contracts/MACI.sol
contracts/contracts/Poll.sol
contracts/contracts/trees/AccQueue.sol
contracts/ts/genMaciState.ts

Instead of allowing concurrent polls where users must signup for each poll, this PR aims to allow on chain proof verification for a multiple poll instances with the same set of users.
Testing run `cli/testMultiplePoll.sh`

Fix proof generation for subsequential polls

---

contracts/contracts/MACI.sol

Unit tests are a bit of a challenge since hardhat will throw an error if you try deploying a contract factory without a properly linked library

Add check for poseidon libs in constructor

---

.gitignore
cli/test.sh
cli/test2.sh
cli/test3.sh
cli/test4.sh
cli/test5.sh
cli/test6.sh
cli/testKeyChange.sh
cli/testMultiBatches.sh
cli/testMultiplePoll.sh
cli/ts/genProofs.ts
cli/ts/proveOnChain.ts
integrationTests/ts/__tests__/suites.ts

When there are many messages, there will be many batches of proofs to store. Previously, MACI saved them in a single JSON file, but clrfund round 8 taught us that if this file gets too large, we won't be able to easily parse it due to the string length limit in Nodejs.
As such, this PR makes genProofs save each proof in its own file in a user-specified proofs directory.
Addresses https://github.com/appliedzkp/maci/issues/316

Save each proof in its own file, rather than one big proofs.json

---

Dockerfile

Hey, I've been testing the `genProofs` and `proveOnChain` scripts using the Docker image with the params files that we have in clrfund from the trusted setup https://gateway.pinata.cloud/ipfs/QmWSxPBNYDtsK23KwYdMtcDaJg3gWS3LBsqMnENrVG6nmc.
The scripts failed with the debian `node:15.8.0-buster` image we are using atm. More context of this error here: https://github.com/clrfund/monorepo/issues/417
@daodesigner told me to test them using ubuntu 21.04 since those params files were built using that OS and indeed, they worked fine.
I've created this PR to use that version which seems to be using a newer version of libc. And I kept the same node version we are using (`15.8.0`).
Note: I'm targeting the `master` branch...let me know in case you want me to change that.
Thanks!

Use of ubuntu 21.04 in docker image

---

contracts/ts/__tests__/AccQueue.test.ts
contracts/ts/__tests__/MACI.test.ts
contracts/ts/__tests__/SignUpGatekeeper.test.ts
core/ts/MaciState.ts

- fixes bug in message processing when batch size > numMessages submitted to correctly handle no-ops in maci state generation
- fixes broken tests
Fixes #377

fix: process messages and handle no-ops in maciState object

---

circuits/circom/processMessages.circom

Let's revert the changes. There are two changes between commit https://github.com/appliedzkp/maci/commit/fcd9d919b74648eab012ca26491851aacc2e26e2 and latest v1 branch:
1. add stateRootQip check for each leaf in processMessages. it will check the leaf is included in the stateTree.
2. change isMessageValid to transformer.isValid check
- For the first item, in processOne template, this leaf inclusion check is already added, i.e. processMessages will call processOne for every message and then leaf inclusion check is done inside processOne. so this change is redundant.
- For the second item, isMessageValid includes two checks: one for transformer.isValid, one checks there are enough voiceCredit. I think we should also keep the original check for voiceCredit

revert stateRootQip check

---

.github/workflows/circuit-build.yml
.github/workflows/contracts-build.yml
.github/workflows/core-build.yml
.github/workflows/crypto-build.yml
.github/workflows/domainobjs-build.yml
README.md

This PR enables CI to validate sub-packages for every PR and commits to the `v1` branch.
When pull reqeust opened to the`v1` branch or code is pushed to the`v1` branch, it will trigger GitHub Actions. Then GitHub Actions runs tests for:
- Circuit
- Contracts
- Core
- Crypto
- Domainobjs

Add CI workflows to test subpackages

---

.github/workflows/circuit-build.yml
.github/workflows/e2e-nightly-test.yml
.github/workflows/e2e.yml
cli/ts/genProofs.ts
cli/ts/utils.ts

This PR add checks for `.dat` file (one of the artifact of compiled circuit and it is required to execute witness generation) and print error if it doesn't exist.
Currently, when user execute `genProofs` command without `.dat` file,  they will got ambiguous error doesn't address explicitly they missed `.dat` file.

Check if `.dat` file exists when running `genProofs` command

---

contracts/contracts/MACI.sol
contracts/ts/genEmptyBallotRootsContract.ts

Currently, it is hard to recognize that the **first argument** of `IncrementalQuinTree`'s constructor is for what. So this PR makes it clear by declaring variable--therefore user could easily recognize which value should they change when they are going to use a value other than 10 for `stateTreeDepth` value -- rather than directly pass the numeric literal to constructor's argument.
The first argument of `IncrementalQuinTree` should be modified to the same value as `stateTreeDepth` of the circuit to be  used. Otherwise, user could get an error when running `proveOnChain` command like following when a user uses 7 as a `stateTreeDepth` value but left `ballot tree depth` value to 10:
```
Submitting proofs of message processing...
Error: currentSbCommitment mismatch.
0
{
provider: …
```

Make ballot tree depth value to be stand out

---

.github/scripts/run-e2e-tests.sh
README.md
circuits/circom/trees/incrementalMerkleTree.circom
cli/README.md
docs/installation.md
docs/trustedsetup.md
old_specs/03_circuits.md
package.json
server/README.md

This PR reflect the org name change happened last Friday:
https://github.com/appliedzkp -> https://github.com/privacy-scaling-explorations

Reflect GitHub Organization name change

---

cli/benchmark.sh
cli/bsc_test.sh
cli/deploy_test.sh
cli/test.sh
cli/test1.sh
cli/test2.sh
cli/test3.sh
cli/test4.sh
cli/test5.sh
cli/test6.sh
cli/testKeyChange.sh
cli/testMultiBatches.sh
cli/testMultiBatches1.sh
cli/testMultiplePoll.sh
cli/testMultiplePoll1.sh
cli/testMultiplePoll2.sh
cli/ts/deployPoll.ts
docs/cli.md
integrationTests/integrations.yml
integrationTests/ts/__tests__/suites.ts
server/admin.sh

Figured out that `max-vote-options` is not configurable, its strictly binded with `vote-option-tree-depth`. So this PR removes this option and set this value as `5 ** vote-option-tree-depth`.
If we give a value for `--max-vote-options` smaller than `5 ** vote-option-tree-depth`, following error would occur:
```
Generating proofs of message processing...
Progress: 1 / 1
Generating proofs of vote tallying...
terminate called after throwing an instance of 'std::runtime_error'
what():  Error loading signal currentPerVOSpentVoiceCredits: Not enough values
Aborted (core dumped)
terminate called after throwing an instance of 'std::runtime_error'
what():  Error loading signal currentPerVOSpentVoiceCredits: Not enough values
Aborted (core dumped)
/home/ubuntu/maci/circuits/ts/index.ts:44
throw new …
```

Remove `--max-vote-options` from `deployPoll` command

---

integrationTests/ts/__tests__/suites.ts

It fixes the test failure of https://github.com/privacy-scaling-explorations/maci/pull/463.

test: specify `regMatch` keyword clearly

---

core/ts/__tests__/MaciState.test.ts

Fixes https://github.com/privacy-scaling-explorations/maci/issues/408. The bug has came from the test code, not from MACI.
Credit of the fix: @chaosma (https://github.com/privacy-scaling-explorations/maci/issues/408#issuecomment-1207108846)

Fix the flakiness of `core` package test

---

circuits/ts/__tests__/TallyVotes.test.ts

This PR fixes the bug of test case of `maci-circuits`(fixes #498).

test(circuits): fix index to prevent assigned 0

---

Dockerfile

This PR updates the `Dockerfile` to Ubuntu 22.04 LTS to fix package sources build errors and a revising the Node v15 installation to Node v12, as documented.

Update: dockerfile to use ubuntu 22.04 and Node 12.18.1

---

.github/workflows/e2e.yml
.github/workflows/release.yml
.github/workflows/reusable-e2e.yml
README.md
cli/package-lock.json
contracts/package-lock.json
core/package-lock.json
domainobjs/package-lock.json
integrationTests/package-lock.json
package-lock.json
server/package-lock.json

* Publish changed npm package(s) when PR has been merged into `v1` branch
* Draft a release and publish npm packages when tag has been pushed
The main development branch(currently, `v1`) contains latest merged PR could be imported using `ci` tag in `package.json`:
```
"dependencies": {
maci-circuits": "ci"
]
```
Otherwise, use `0.0.0-ci.${COMMITHASH}` tag to import specific commit (e.g. `0.0.0-ci.90b1965`)
* Refactor CI to use reusable workflow
* `.github/workflows/e2e.yml` contains all CI pipeline triggering scenario 
(See [CI triggers](https://github.com/privacy-scaling-explorations/maci/wiki/CI-Pipeline#pipeline-triggers) for more detail)
>  Ensure that every commit to version control triggers the automated creation of packages that can be deployed to any environment using only …

CI: add a workflow for npm package publishing

---

circuits/circom/float.circom
circuits/circom/subsidy.circom
contracts/contracts/TopupCredit.sol

* use a similar algorithm which has more relax condition for inputs 
* check divisor not equal zero
* check inputs not overflow for float division and representation
* check multiplication a*b not overflow
*  to avoid subsidy formula overflow, add comments on voice credit contracts

rewrite float division circuit

---

integrationTests/ts/__tests__/suites.json
integrationTests/ts/__tests__/suites.ts
integrationTests/ts/__tests__/utils.ts

Changes:
* test harness can verifies subsidy result
* added one test case 
* now test harness verifies spent voice credit(s) per user as well
* fix wrong verification logic of tally

test: verify subsidy result

---

circuits/package-lock.json
circuits/package.json
cli/package-lock.json
cli/package.json
contracts/contracts/trees/AccQueue.sol
contracts/package-lock.json
contracts/package.json
contracts/ts/buildPoseidon.ts
crypto/package-lock.json

Upgraded extra dependencies such as snarkjs.

fix(maci): upgraded snarkjs and other dependencies

---

docs/circuits.md

[Third parameter of TallyVotes circuit is voteOptionTreeDepth](https://github.com/privacy-scaling-explorations/maci/blob/v1/circuits/circom/tallyVotes.circom#L16).

docs: fix description of circuit parameter

---

.github/workflows/circuit-build.yml
.github/workflows/contracts-build.yml
.github/workflows/core-build.yml
.github/workflows/crypto-build.yml
.github/workflows/domainobjs-build.yml
.github/workflows/e2e.yml
.github/workflows/gh-pages.yml

This PR reflects that the `v1` branch is now deprecated.

ci: update the triggers to reflect latest branching strategy

---

circuits/circom/trees/incrementalQuinTree.circom
circuits/circom/utils.circom

Due to CI issue, separate the commits into two PR.
- remove unnecessary condition check in incrementalQuinnTree.circom
- added SafeLessThan, SafeGreaterThan circuit for safety use comparator circuits
- replaced LessThan/GreaterThan usages by Safe ones. This includes security audits items as well as some other places. Only except is float.circom it involves too much computation for subsidy.

Security audit 1

---

circuits/circom/messageValidator.circom
circuits/circom/processMessages.circom
circuits/circom/trees/incrementalQuinTree.circom
circuits/circom/utils.circom

* remove unnecessary condition check in incrementalQuinnTree.circom
* added SafeLessThan, SafeGreaterThan circuit for safety use comparator circuits
* replaced LessThan/GreaterThan usages by Safe ones. This includes security audits items as well as some other places. Only except is float.circom it involves too much computation for subsidy.

security audits 2

---

cli/ts/index.ts

Fix: #640 
This PR adds a new feature to maci-cli that will print a message to the console when it is unable to find a hardhat config file in the project directory. For example:
```
$ maci-cli
ERROR: File not found: hardhat.config.js
maci-cli requires a hardhat.config.js file to be present in your project directory in order to function properly. This file is used by hardhat to deploy contracts. Please make sure that the hardhat.config.js file is present in your project directory and try again. If the file is missing, please create one using the Hardhat documentation: https://hardhat.org/hardhat-runner/docs/config
```
This message will help users quickly identify why their hardhat commands are failing and prompt them to create a new config file if necessary.

chore(maci-cli): check hardhat config file

---

cli/ts/deployPollWithSigner.ts
cli/ts/fundWallet.ts
cli/ts/index.ts
integrationTests/package.json
integrationTests/scripts/download_zkeys.sh
integrationTests/ts/__tests__/deployPollWithRandomSigner.test.ts
integrationTests/ts/__tests__/suites.ts

The test case duplicates the existing deployPoll.ts script and change it to accept a new argument, a private key of a signer which will deploy the poll.
The test case first run the first test case from the existing integration test suite to setup the environment (like deploying MACI and Poll contracts). After the first poll is tallied and finalized, the test case start a new poll using a randomly created wallet.
How to run the test:
1) Setup MACI as described in the readme file
2) run the test
```
cd integrationTests
npm run download-zkeys
npm run test-deployPoll
```
The test should pass, which means a new poll was successfully created by a random wallet.

Test case to show anyone can deploy poll

---

old_specs/01_introduction.md

fix a typo in doc: interchangably-> interchangeably

docs: fix typo

---

cli/ts/proveOnChain.ts
cli/ts/utils.ts
cli/ts/verify.ts

Before: only error message has been printed
After: error message and relevant values will be printed

refactor(cli): print relevant values when comparing fails

---

.gitignore
circuits/package-lock.json
circuits/package.json
cli/package-lock.json
cli/package.json
common/package-lock.json
contracts/package-lock.json
contracts/package.json
core/package-lock.json
core/package.json
crypto/package-lock.json
domainobjs/package-lock.json
domainobjs/package.json
integrationTests/package-lock.json
integrationTests/package.json
package-lock.json
package.json
server/package-lock.json
server/package.json
tsconfig.json
typedoc.json

feat(typedoc) - add typedoc to the repo

---

circuits/ts/__tests__/ProcessMessages.test.ts
circuits/ts/__tests__/TallyVotes.test.ts
circuits/ts/__tests__/utils.ts
cli/ts/create.ts
cli/ts/deployPoll.ts
contracts/README.md
contracts/contracts/MACI.sol
contracts/package.json
contracts/scripts/compileSol.sh
contracts/scripts/writeEmptyBallotRoots.sh
contracts/tests/MACI.test.ts
contracts/tests/MACI_overflow.test.ts
contracts/tests/SignUpGatekeeper.test.ts
contracts/ts/deploy.ts
contracts/ts/genEmptyBallotRootsContract.ts
contracts/ts/genMaciState.ts
contracts/ts/utils.ts
core/ts/MaciState.ts
core/ts/__tests__/MaciState.test.ts
core/ts/index.ts
integrationTests/ts/__tests__/suitesUtils.ts

We do not want to hardcode the stateTreeDepth in the smart contracts, but instead we want to pass them as arguments.
Changes:
* in the smart contract this is an immutable param thus passed in the constructor
* MaciState.ts and Poll.ts take them as constructor argument
* in tests we hardcode to 10 for the sake of testing
* contracts package.json's script `compileSol` takes an additional parameter so that we can compile the trees contracts with the correct params

feat(state-tree-depth) - ensure stateTreeDepth is not hardcoded 

---

.github/workflows/circuit-build.yml
.github/workflows/contracts-build.yml
.github/workflows/core-build.yml
.github/workflows/crypto-build.yml
.github/workflows/domainobjs-build.yml
.github/workflows/e2e.yml
.github/workflows/gh-pages.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/reusable-e2e.yml

This PR introduces a nightly proving key generation workflow. It will help us maintain the ability to generate the proving key and ensure that it remains functional even if no new changes are made to the circuits. It provides an additional layer of assurance for the codebase and allows others to build their own proving keys without any issues.

ci: nightly proving key generation workflow

---

website/versioned_docs/version-v0.x/contract.md

I've spotted a few minor errors in the document.
Line 166: if e,d, and c are valid then the weight sums up to 11, not 10.
Line 168: (b) gives a nonce of (1) not (2)
Line 175: There is no vote (c), only (a) and (b). Rename (c) to (b).
I've also unified two styles used to list votes `a.` and `a)` to `(a)` (so it is consistent with the description). Moreover, I have added `- (a)` for a better post-rendering list 
readability.

fix: errors in 02_contract.md

---

crypto/package-lock.json
crypto/package.json
crypto/ts/@types/optimisedmt.d.ts

The version of [optimisedmt](https://github.com/weijiekoh/optimisedmt) currently in use is outdated, and the d.ts (declarations) file has some mistakes. This PR fixes these issues (fix #874) by
*  upgrading to version 0.0.9. The upgrade includes adding the `getLeaf(index: number)` and `equals()` methods
* generating a new d.ts directly from the repo's code

fix(optimisedmt) - update package to the latest version and generate the correct d.ts file

---

website/blog/2023-01-18-maci-v1.1.1.md

Current links to `https://github.com/privacy-scaling-explorations/maci/tree/v1/` are broken - looks like that tree no longer exists.
h/t to @crisgarner for reporting!
https://discord.com/channels/943612659163602974/1164613809730748507/1182043669398827059

fix: update GH repo links to v1.1.1 tag

---

.eslintignore
.husky/commit-msg
commitlint.config.js
package-lock.json
package.json

This is in reference to us establishing our GH processes (#847). Users can easily commit using convential messages in an interactive way by running:
`npm run commit`
Furthermore, pre-commit hooks will ensure that the commit message follows the guideline.

chore(cz): update commitizen (cz) and add scripts around it

---

cli/ts/commands/verify.ts
cli/ts/utils/verifiers.ts
contracts/contracts/Tally.sol
crypto/ts/index.ts
crypto/ts/utils.ts

This PR adds the functions to the new Tally contract as I think they were accidentally removed from code refactoring as they were available in v0.10 and v1.1 (incorrect implementation, see PR #742 )
Clrfund uses these functions to verify the tally results in the tally.json file on-chain as part of the round finalization and when recipients invoke the `claimFunds` function.
Note: I moved the standalone test `deployPollWithRandomSigner.test.ts` in the `suites.test.ts` as it was failing with `nonce` error caused by running the tests in parallel.
Run the integration test suites to test the new functions:
```
cd integrationTests
npm run test
```

Add verifyTallyResult, verifyPerVOSpentVoiceCredits, verifySpentVoiceCredits

---

cli/package.json
cli/tests/keyChange.test.ts
core/ts/__tests__/MaciState.test.ts
website/versioned_docs/version-v1.x/key-change.md
website/versioned_docs/version-v1.x/troubleshooting.md

Currently, it is not clear how the key change mechanism works (or doesn't), hence this PR aims to provide some clarification on this front, by adding docs and test cases.
This is in reference to this: https://github.com/privacy-scaling-explorations/maci/issues/717

tests(key-change): add tests and docs related to MACI's key change

---

README.md

This PR fixes markdown syntax in README.md

docs: fix markdown syntax in README.md

---

package-lock.json
package.json
typedoc.json
website/.gitignore
website/docusaurus.config.ts
website/src/scripts/setupSolidityDocs.ts
website/src/scripts/setupTypedoc.ts
website/src/scripts/utils.ts
website/tsconfig.json

**Description**
Try the package [docusaurus-plugin-typedoc](https://www.npmjs.com/package/docusaurus-plugin-typedoc) at the beginning, it could automatically generate markdown files for typedocs, and put them inside `doc/` folder, which is default for the **Next** version document in Docusaurus. Also the sidebar will also be auto-generated.
However, we will need to do something before we actually start or build the docusaurus:
1. replace the package folder link in `README.md` (which should be the index page of typedoc) to github links. (currently we are doing it in the `setupTypedoc.ts`, by replacing the route in html file ➡️ https://github.com/privacy-scaling-explorations/maci/blob/88bfae966ec602592691b3d3ae8ad53e4a4c9a6c/website/src/scripts/setupTypedoc.ts#L38
2. `docs/` is not the …

docs(typedoc): Typedoc Indexing

---

.github/scripts/ceremony-param-tests-c-witness.sh
.github/scripts/ceremony-param-tests.sh
.github/scripts/download-ceremony-artifacts.sh
.github/workflows/nightly-ceremony.yml
circuits/circom/test/ceremonyParams/processMessages_test.circom
circuits/circom/test/ceremonyParams/tallyVotes_test.circom
circuits/package.json
circuits/ts/__tests__/CeremonyParams.test.ts
cli/ts/commands/genProofs.ts
cli/ts/commands/setVerifyingKeys.ts
cli/ts/index.ts

This PR adds a new CI workflow that can be used to run certain e2e tests with the process messages and tally votes zkeys generated during MACI's v1 trusted setup ceremony.
It also adds tests which use the params used in the ceremony (6,8,2,3 and 6,2,3) both e2e and on the circuits package
fix #840

test(ceremony): test ceremony artifacts and params

---

cli/package-lock.json
cli/package.json
core/package-lock.json
core/package.json
crypto/package-lock.json
crypto/package.json
domainobjs/package-lock.json
domainobjs/package.json

setup code coverage for TS packages using [istanbul (nyc)](https://istanbul.js.org/)
fix #931

test(coverage): setup coverage for TS packages

---

cli/ts/commands/proveOnChain.ts
contracts/contracts/MACI.sol
contracts/contracts/Subsidy.sol
contracts/tests/MACI.test.ts
core/ts/MaciState.ts

currently the blank state leaf is not counted as one signup, and thus we could go over the supported amount of signups (based on the circuits parameters) by 1, potentially preventing one voters' votes from being tallied
fix #947

fix(signups): ensure we account for the blank state leaf

---

circuits/ts/index.ts
circuits/ts/proofs.ts
circuits/ts/types.ts
cli/tests/e2e.subsidy.test.ts
cli/tests/e2e.test.ts
cli/tests/keyChange.test.ts
cli/tests/utils.ts
cli/ts/commands/genProofs.ts

Remove `isArm` check in circuits and instead accept a parameter to decide which witness type to use. Made appropriate changes in tests and cli. 
This allows to use wasm witness in an intel chip as well should this be preferred.

feat(proofs): add preferred witness type in circuit's genProof function

---

.github/scripts/ceremony-param-tests-c-witness.sh
domainobjs/package.json
domainobjs/ts/__tests__/ballot.test.ts
domainobjs/ts/__tests__/commands.test.ts
domainobjs/ts/__tests__/keypair.test.ts
domainobjs/ts/__tests__/message.test.ts
domainobjs/ts/__tests__/privateKey.test.ts
domainobjs/ts/__tests__/publicKey.test.ts
domainobjs/ts/__tests__/stateLeaf.test.ts
domainobjs/ts/__tests__/verifyingKey.test.ts
domainobjs/ts/privateKey.ts

Implement more unit tests in the domainobjs package to ensure the code is thoroughly tested.
fix #929

test(domainobjs): implement unit tests for the domainobjs package

---

contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/contracts/Poll.sol
contracts/contracts/PollFactory.sol
contracts/contracts/SignUpToken.sol
contracts/contracts/Subsidy.sol
contracts/contracts/Tally.sol
contracts/contracts/TopupCredit.sol
contracts/contracts/VkRegistry.sol
contracts/contracts/gatekeepers/FreeForAllSignUpGatekeeper.sol
contracts/contracts/gatekeepers/SignUpTokenGatekeeper.sol
contracts/contracts/initialVoiceCreditProxy/ConstantInitialVoiceCreditProxy.sol
contracts/contracts/trees/AccQueue.sol
contracts/contracts/utilities/Utilities.sol
contracts/tests/Subsidy.test.ts
contracts/tests/Tally.test.ts

refactor(contracts): smart contracts optimizations

---

integrationTests/ts/__tests__/integration.test.ts

Ensure integration tests use the correct user keys, in particular when performing key changes.
re:  #910

test(integration): ensure integration tests are using the correct user keys

---

.github/CODEOWNERS
.github/dependabot.yml

This PR adds more automation for dependency management and adds reviewers automatically for PR.
N/A
Related to #793

chore: add dependabot and codeowners

---

commitlint.config.js

No need to lint commit messages for dependabot
N/A
Related to #793

chore: ignore dependabot commit messages for linting

---

circuits/package.json
circuits/tsconfig.build.json
cli/package.json
cli/tsconfig.build.json
contracts/package.json
contracts/tsconfig.build.json
core/package.json
core/tsconfig.build.json
crypto/package.json
crypto/tsconfig.build.json
domainobjs/package.json
domainobjs/tsconfig.build.json

Use separate tsconfig for build and development
N/A
Related to #781

chore(cli): optimize bundle size

---

.github/scripts/ceremony-param-tests-c-witness.sh
.github/workflows/e2e.yml
cli/package-lock.json
cli/package.json

There have been some issues in the nightly workflows, which compile circuits and generate zkeys from scratch to ensure the whole process works as expected.
This PR fixes two issues:
* having removed snarkjs from the cli package we cannot use zkey-manager anymore to generate new zkeys - this was added back as a dev dependency
* the nightly workflow with the ceremony params has a very small poll duration set causing it to fail
re #977

fix(nightly): add back snarkjs to cli as dev dependency and fix poll duration

---

.github/workflows/e2e.yml
.github/workflows/nightly-ceremony.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
contracts/scripts/compileSol.sh
contracts/scripts/writeEmptyBallotRoots.sh
contracts/ts/genEmptyBallotRootsContract.ts

Add environment variable so that contracts can be built using a different state tree depth param, and thus allow for publishing to npm contracts that work with the ceremony params
close: #973

chore(publish): fix publishing scripts to publish contracts with ceremony params

---

.github/workflows/e2e.yml
.github/workflows/release.yml

When `stateTreeDepth` is different from 10, `npm run build` will generate a different `emptyBallotRootsContract.sol` file which without being staged for commit, will prevent lerna from publishing it to npm.

fix(publish): ensure we commit unstaged files first

---

cli/.env.template
cli/hardhat.config.ts

- Add `ETH_PROVIDER` in the `.env.template` file.
- import `dotenv` package to enable `hardhat.config.ts` to read environmental variables.
close issue #995.

feat(cli): enable environmental variables

---

core/ts/Poll.ts
core/ts/__tests__/MaciState.test.ts
core/ts/__tests__/Poll.test.ts
core/ts/__tests__/e2e.test.ts
core/ts/__tests__/utils.ts
core/ts/__tests__/utils/constants.ts
core/ts/__tests__/utils/utils.ts
core/ts/utils/utils.ts

This PR adds end-to-end test cases of the off-chain state machine, focusing on sanity checks.
Related to #792

test(core): e2e test cases core maciState/Poll

---

website/blog/2021-10-12-maci-v1.md

fixed header in release post

---

.github/CODEOWNERS
.github/workflows/codeql.yml
.github/workflows/contracts-build.yml
.github/workflows/core-build.yml
.github/workflows/crypto-build.yml
.github/workflows/domainobjs-build.yml
.prettierignore
website/versioned_docs/version-v1.x/versioning.md

Add CodeQL boilerplate config and remove master branch from workflow files
N/A
Related to #793

chore: enable codeql and workflows cleanup

---

.github/workflows/release.yml

Use `pnpm exec` instead of `npx`
@0xmad I was reviewing #1005 & noticed this was the only remaining place we use `npx`. Figured it wouldn't hurt to update this for consistency but LMK if I'm missing something
#1005

chore: use pnpm instead of npx

---

cli/ts/cliInit.ts
cli/ts/index.ts

Fix for cli run without specifying hardhat conifg
N/A
Related to #1011

fix(cli): add env initialization for hardhat conifg

---

circuits/ts/compile.ts
circuits/ts/proofs.ts

Fix CodeQL errors
N/A
Related to #1007

fix(circuits): replace execSync with execFileSync

---

core/tsconfig.build.json
crypto/tsconfig.build.json

Exclude benchmarks folder from build.

fix(publishing): do not publish benchmarks folder

---

circuits/package.json
cli/package.json
contracts/package.json
core/package.json
crypto/package.json
domainobjs/package.json
integrationTests/package.json

Ensure we publish the correct files by setting the correct paths inside package.json

fix(publish): ensure we publish the correct files

---

cli/ts/commands/genProofs.ts
contracts/ts/genMaciState.ts

Ensure the start block is not overriden by the tx hash check. Also ensure we fetch logs at least for 1 block if fromBlock is equal to lastBlock
fix #1043 fix #1044

fix(fetch): fix bugs related to logs fetching

---

cli/testScript.sh
cli/ts/commands/proveOnChain.ts
cli/ts/utils/storage.ts

Do no throw when the contract addresses file is not present but a contract address has been provided
fix #1039

fix(cli): prioritize contract addresses params

---

website/blog/2024-01-18-roadmap.md
website/blog/index.md

Add new blog post with MACI roadmap updates
N/A

feat: add new post on roadmap updates

---

README.md

Small README tweaks to clarify that users should refer to our documentation
N/A, feedback from Discord

docs: clarify installation instructions in readme

---

circuits/ts/compile.ts

Currently, compiling the c witness generator will fail because execFileSync commands share no context, thus the second command will still run in the original directory, not the one where the first command moved to.

fix(build): fix bug that prevented c witness from being compiled

---

cli/ts/commands/proveOnChain.ts
contracts/contracts/MessageProcessor.sol

Remove redundant check from message processor circuit and proveOnChain cli command. 
Core:  https://github.com/privacy-scaling-explorations/maci/blob/dev/core/ts/Poll.ts#L436-L451
Redundant check: 
https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L97-L101
```
if (r == 0) -> (numMessages / messageBatchSize) * messageBatchSize would just be numMessages
```

fix(message-batch-index): remove redundant check

---

cli/ts/commands/publish.ts
cli/ts/commands/signup.ts

hardcoded gas limit might prevent transaction from succeeding on certain networks
fix #1086

fix(cli): remove hardcoded gas limit from signup and publish

---

cli/ts/commands/genLocalState.ts

In genLocalState, we check that a poll contract is present in a local address store file. This is not necessary as given a pollId and a maci contract address, the address of the poll can be found on chain.
fix #1084

fix(cli): remove redundant local check for poll address

---

website/src/css/custom.css

as described in #1071 .
fix #1071.
actually I should modify `--docsearch-hit-active-color` as black-like color, but it refers to `ifm-color-white` in the **dark** mode, I tried to modify it directly but failed, so can only modify the `ifm-color-white`. 
It's so weird, maybe just a temporal solution.

fix: dark mode search result

---

circuits/ts/__tests__/CeremonyParams.test.ts
circuits/ts/__tests__/ProcessMessages.test.ts
circuits/ts/__tests__/TallyVotes.test.ts
contracts/tests/AccQueue.test.ts
contracts/tests/AccQueueBenchmark.test.ts
contracts/tests/utils.ts
crypto/ts/AccQueue.ts
crypto/ts/__tests__/utils.ts
crypto/ts/types.ts

Use map instead of 2d array as internal data structure for AccQueue and make class props access stricter.
N/A
Closes #1030

fix(crypto): get rid of potential prototype polution

---

cli/tests/constants.ts
cli/ts/commands/deployPoll.ts
cli/ts/commands/proveOnChain.ts
cli/ts/index.ts
cli/ts/utils/interfaces.ts
contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/contracts/Poll.sol
contracts/contracts/PollFactory.sol
contracts/contracts/Subsidy.sol
contracts/contracts/Tally.sol
contracts/contracts/interfaces/IPoll.sol
contracts/contracts/interfaces/IPollFactory.sol
contracts/contracts/utilities/Params.sol
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Poll.test.ts
contracts/tests/PollFactory.test.ts
contracts/tests/Subsidy.test.ts
contracts/tests/Tally.test.ts
contracts/tests/constants.ts
contracts/ts/genMaciState.ts
integrationTests/ts/__tests__/integration.test.ts
integrationTests/ts/__tests__/maci-keys.test.ts

Simplify logic and save gas by computing maxValues and batchSizes within MACI vs passing as parameter to deployPoll.
Also cache variables fetched from the poll contract, and pass around the various functions inside MessageProcessor.
Benefits: 
* Reduction of gas consumption to deploy Poll and various contracts.
* large gas saving in the `processMessages` function
fix #1066

refactor(contracts): remove maxValues from Maci.deployPoll() and instead calculate

---

pnpm-lock.yaml
website/docusaurus.config.ts
website/package.json

as described in #912 .
Install a package for automatically make markdown images zoomable: https://www.npmjs.com/package/docusaurus-plugin-image-zoom
close #912 .

feat: make image zoomable by adding package

---

circuits/ts/__tests__/CeremonyParams.test.ts
circuits/ts/__tests__/ProcessMessages.test.ts
circuits/ts/__tests__/TallyVotes.test.ts
cli/tests/e2e/e2e.test.ts
contracts/contracts/Poll.sol
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Subsidy.test.ts
contracts/tests/Tally.test.ts
contracts/ts/genMaciState.ts
core/package.json
core/ts/MaciState.ts
core/ts/Poll.ts
core/ts/__benchmarks__/index.ts
core/ts/__tests__/Poll.test.ts
core/ts/__tests__/e2e.test.ts
core/ts/__tests__/utils/utils.ts
core/ts/utils/types.ts

prevent new signups from changing the record of users being signed for a specific poll. Instead store this value in the Poll contract after the stateAq is merged. This way, even if a user signs up after the logs are fetched and the state is reproduced offchain, the proof validation will not fail because of a numSignups mismatch.
Changes:
* when calling `mergeMaciStateAq` on the Poll contract, we now save the number of signups on a state variable
* the `numSignUpsAndMessages` function now returns the value from the Poll state and not from the MACI contract so if there's any new signup, this does not affect proof verification later on
* removed the state tree from MaciState. Instead, `MaciState.ts` will store the state leaves only. 
* amended the `copyStateFromMaci` function in `Poll.ts` to …

fix(contracts): save numSignups after merging maciStateAq inside the Poll contract

---

cli/ts/commands/deploy.ts

Fix bug in deploy maci cli command preventing deployment when gatekeeper and voice credit proxy addresses are provided as input.
fix #1105

fix(cli): give priority to gatekeeper and voice credit proxy args

---

contracts/hardhat.config.ts
contracts/package.json
contracts/tasks/deploy/maci/05-poseidon.ts
contracts/tasks/helpers/ContractStorage.ts
contracts/tasks/helpers/ContractVerifier.ts
contracts/tasks/helpers/types.ts
contracts/tasks/runner/deployFull.ts
contracts/tasks/runner/verifyFull.ts

Verification doesn't work for Poseidon contracts
```
0x4B28230fcbe036470D6A11E8849533Cff279874E PoseidonT6: The contract you want to verify was compiled with solidity <0.4.7, but your configured compiler version is: 0.8.10.
```
Related to #1096

chore(contract): add contract verification task

---

cli/testScript.sh
cli/ts/commands/genProofs.ts
core/ts/Poll.ts

Allow to log errors in message processing by accepting a flag into core.processMessages
fix #1135

chore(core): add quiet flag to process messages to log errors

---

contracts/contracts/Tally.sol
contracts/tests/Tally.test.ts

Remove event from `tallyVotes` and instead use a view function to determine on a frontend whether the ballots have been tallied or not.
#1143

feat(tally): remove ballotsTallied event and add view function

---

cli/ts/commands/genProofs.ts
cli/ts/commands/verify.ts
cli/ts/index.ts
cli/ts/utils/interfaces.ts

Simplify the verify command interface by favoring data fetching from the tally data or tally file.
Also add chain id and network name to better identify tally results across chains.
fix #1065 
fix #1085

feat(cli): add relevant information in tally.json to simplify verify interface

---

contracts/contracts/Poll.sol
contracts/contracts/interfaces/IPoll.sol

Remove redundant operation to set msgType to 1. Also use calldata vs memory as we are not modifying the user param anymore.

refactor(contracts): optimize publishMessage by using calldata and removing arg change

---

contracts/contracts/Poll.sol
contracts/contracts/utilities/Utilities.sol

optimize utilities.padAndHashMessage by using inline initialization of array vs using for loop to pad it.

refactor(contracts): optimize utilities.padAndHashMessage

---

core/ts/Poll.ts

Remove redundant code in `genProcessMessagesCircuitInputsPartial`, looping over a potentially large array to create an array copy that is not used

refactor(core): remove redundant code which could slow down processing

---

website/versioned_docs/version-v1.x/cli.md

Update cli docs to show how to generate MACI keys, and amend examples to reflect latest code changes.

docs(cli): update cli docs to reflect latest changes

---

contracts/contracts/MACI.sol
contracts/contracts/Poll.sol

Add the virtual keyword to certain contract functions which could be overridden by projects integrating MACI.
Examples:
* a project like clr.fund might override MACI.signup to accept first a contribution from a user to the QF round
* further checks could be added if wanting to gatekeep message publishing

refactor(contracts): add virtual to functions which could be overridden

---

integrationTests/ts/__tests__/integration.test.ts

Remove wrong except matcher which causes invalid tests to pass.

fix(tests): remove wrong chai matcher from integrationTests

---

circuits/circom/messageValidator.circom
circuits/circom/processMessages.circom
circuits/circom/processMessagesNonQv.circom
circuits/circom/stateLeafAndBallotTransformer.circom
circuits/circom/stateLeafAndBallotTransformerNonQv.circom
circuits/ts/__tests__/ProcessMessages.test.ts
cli/tests/e2e/e2e.test.ts
cli/ts/commands/genProofs.ts
core/ts/Poll.ts
crypto/ts/index.ts
domainobjs/ts/commands/PCommand.ts

Prevent passing unmatched state leaves to censor votes by the coordinator. Instead, ensure that the state leaf sent for each message, is the state leaf at position message.stateIndex within the stateTree. Also, force decryption on the TS message processing, to ensure that a malicious user might not send an invalid message which when decrypted by the circuit (using decryptWithoutCheck and thus possibily failing decryption) would result in a valid stateIndex, causing a DoS on the coordinator which would not be able to generate a proof.
Also, the padding messages are not anymore the last message sent (this.messages[this.messages.length - 1]), but actually an empty command with a state index 0 so that when processed in the circuit, it will have no effect.
cc @kcharbo3 
re #1133

fix(circuits): enforce use of stateIndex from message

---

circuits/circom/messageValidator.circom
circuits/circom/messageValidatorNonQv.circom

Ensure state index checks in `messageValidator` are 0 based

fix(circuits): ensure we account for correct num signups in messageValidator

---

contracts/contracts/Poll.sol
contracts/contracts/interfaces/IPoll.sol

Reduce likeliness of issues in the circuits by constraining at the contract level that vote message are type 1.

fix(contracts): enforce msgType = 1 for vote messages at the contract level

---

contracts/contracts/MACI.sol
contracts/contracts/Poll.sol
contracts/contracts/utilities/Utilities.sol

* Add coordinator pub key sanity check 
* optimize padAndHashMessage
* use >= instead of == for signup/message max value checks
* remove unnecessary state variable numStateLeaves on MACI

refactor(contracts): add audit auggestions

---

contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/contracts/PollFactory.sol
contracts/contracts/Tally.sol
contracts/contracts/TallyFactory.sol
contracts/contracts/TallyNonQv.sol
contracts/contracts/TallyNonQvFactory.sol
contracts/contracts/interfaces/IPollFactory.sol

Ensure contracts integrating MACI can override certain functions, as well as use public for functions which are likely to be called from within an inheriting contract. Also remove private for constants in favour of internal.

refactor(contracts): revisit functions visibility and inheritance

---

contracts/contracts/MACI.sol
contracts/contracts/Poll.sol
contracts/tests/MACI.test.ts

prevent user DoS the stateAq tree merging. Currently a user could signup (gatekeeper allowing) after the subtrees have been merged, and prevent a coordinator from calling `mergeStateAq` without having to call `mergeStateAqSubRoots` again.

fix(contracts): prevent user DoS the stateAq tree merging

---

contracts/contracts/Tally.sol

Set public to Tally.isTallied() so it can be called from inheriting contracts too

refactor(contracts): add public to Tally.isTallied

---

cli/tests/e2e/e2e.test.ts

Remove `.only` for cli tests
N/A
N/A

fix(cli): run all the tests for package

---

crypto/ts/__tests__/Crypto.test.ts
crypto/ts/keys.ts
domainobjs/ts/__tests__/privateKey.test.ts
domainobjs/ts/privateKey.ts
domainobjs/ts/publicKey.ts

genPrivKey could generate a random seed vs a babyjubjub compatible value, to remove any unnecessary operations. As mentioned in the related issue, the seed is formatted correctly in the code before being used.
fix #407

refactor(crypto): modify genPrivKey to generate a random seed

---

contracts/contracts/Poll.sol
contracts/tests/Poll.test.ts

Allow to submit a message batch with n numbers of messages and encPubKeys

feat(poll): add message batch submission

---

circuits/circom/processMessages.circom
core/ts/Poll.ts
website/versioned_docs/version-v1.x/topup.md

Currently, the `validCreditBalance` component output is not used in the topup calculation. In this PR, we use the output of this component to switch between keeping the previous balance or using the new one. 
Furthermore, some documentation around the topup feature is also added in the doc website.

fix(topup): check valid new state leaf balance

---

contracts/ts/index.ts

Export deployContractsWithLinkedLibraries

chore(contracts): export  deployContractsWithLinkedLibraries

---

website/versioned_docs/version-v1.x/overview.md

docs: update overview.md

---

.github/workflows/release.yml

Fix issue with tag publishing not working due to missing git config directive.

fix(ci): fix tag publishing workflow

---

cli/tests/unit/publish.test.ts
cli/ts/commands/index.ts
cli/ts/commands/publish.ts
cli/ts/index.ts
cli/ts/sdk/index.ts
cli/ts/utils/index.ts
cli/ts/utils/interfaces.ts

Add publish batch method for maci-cli sdk.
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/7

feat(cli): add publish batch method for cli sdk

---

cli/ts/commands/signup.ts

Get state index from event args array
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/7

fix(cli): read state index from event args

---

.github/workflows/release.yml

[Recent attempt](https://github.com/privacy-scaling-explorations/maci/actions/runs/8064499516/job/22028505253) to publish packages to npm failed and the root of the problem was our use of `lerna publish from-git`, which is designed to publish packages tagged in the current commit. However, our CI process includes an additional commit after tagging (see [here](https://github.com/privacy-scaling-explorations/maci/blob/d3952dd886c8e6692a36f6e83d85a751b19281b1/.github/workflows/release.yml#L55-L58)), meaning the current commit wasn't tagged at the time of publishing. This discrepancy led to Lerna's inability to publish using the `from-git` method.
To address the issue, this PR updates lerna to switch from `from-git` to [`from-package`](https://github.com/lerna/lerna/blob/main/libs/commands/pub …

fix: fix unable to publish package

---

website/blog/2023-01-18-maci-v1.1.1.md
website/blog/2024-02-28-maci-v1.2.0.md
website/versioned_docs/version-v1.x/introduction.md

Blog post for upcoming MACI v1.2.0 release
#856

Docs/release post v1.2

---

cli/ts/commands/publish.ts

Generate ECDH shared key for batch message publish only one time.
N/A
N/A

fix(cli): generate ecdh shared key only one time

---

cli/tests/unit/publish.test.ts
cli/ts/commands/publish.ts
cli/ts/utils/interfaces.ts

feat(cli): return additional data from publish batch command

---

.github/scripts/download-ceremony-artifacts.sh
circuits/ts/__tests__/CeremonyParams.test.ts
cli/tests/ceremony-params/ceremonyParams.test.ts
cli/tests/constants.ts

Update ceremony params tests to use new artifacts, as well as adding non qv tests
fix #1272

test(ceremony): update ceremony params tests

---

website/versioned_docs/version-v1.x/installation.md

- update instruction for installing `rapidsnark`
close #1102

docs: update rapidsnark installation instruction

---

website/versioned_docs/version-v1.x/poll-types.md

Add a page in the doc website explaining how to run quadratic polls and non quadratic polls.
fix #1273

docs(poll types): add docs describing type of polls (qv/non qv)

---

cli/tests/constants.ts

Fix nightly workflow failing due to wrong artifacts filenames.

fix(nightly): fix issue with artifacts not found due to wrong filename

---

website/versioned_docs/version-v1.x/audit.md
website/versioned_docs/version-v1.x/circuits.md
website/versioned_docs/version-v1.x/contracts.md
website/versioned_docs/version-v1.x/coordinator-processing.md
website/versioned_docs/version-v1.x/installation.md
website/versioned_docs/version-v1.x/integrating.md
website/versioned_docs/version-v1.x/key-change.md
website/versioned_docs/version-v1.x/primitives.md
website/versioned_docs/version-v1.x/purpose.md
website/versioned_docs/version-v1.x/spec.md
website/versioned_docs/version-v1.x/testing-in-detail.md
website/versioned_docs/version-v1.x/testing.md
website/versioned_docs/version-v1.x/workflow.md

docs: fix typos

---

core/package.json
pnpm-lock.yaml

Fix build for core package
N/A
N/A

fix(core): add typescript dev dependency to fix build

---

.github/workflows/gh-pages.yml

Prevent deploying to the prod website on pull requests, but only on pushes to dev. We have previews on netlifly anyways.

docs(website): remove deployment on pull request

---

contracts/tests/EASGatekeeper.test.ts

Fix eas_gatekeeper tests failing due to not waiting for the txs to be completed on a forked network.

test(contracts): fix eas_gatekeeper tests

---

cli/ts/commands/signup.ts

Add initial voice credits for poll sdk method
N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/pull/39

feat(cli): add initial voice credits from signup event

---

core/ts/Poll.ts

Avoid printing confusing message on core.Poll when processing the message at position 0
fix #1134

chore(core): do not print warning on failed decryption of message 0

---

contracts/tasks/deploy/maci/10-maci.ts
contracts/tasks/deploy/poll/01-poll.ts
contracts/tasks/helpers/ContractStorage.ts
contracts/tasks/helpers/ContractVerifier.ts
contracts/tasks/helpers/types.ts
contracts/tasks/runner/verifyFull.ts

Add missing deployed contract to json file for verififcation
N/A
N/A

chore(contracts): add acc queue contract to deployed contracts

---

cli/tests/unit/poll.test.ts
cli/ts/commands/poll.ts
cli/ts/utils/interfaces.ts

Add provider object to read poll data without signer
N/A
N/A

feat(cli): add provider fallback for poll data sdk method

---

cli/ts/index.ts

In the cli the command `genLocalState` has ha '-o' parameter used to specifiy the path where to write the local state. 
For other commands '-o' represented the pollId and the parameter required to be parsed into an integer but here trying to parse a path does nto allow to specify the path ending up to store the local store in a file called 'NaN'
--

fix: for genLocalState '-o' represents the path where to write the local state and not the pollId and must be be parsed as int.

---

crypto/ts/__tests__/AccQueue.test.ts

Add unit test for `copy` and `insertSubTree` method  in AccQueue.
all tests are passed
N/A
N/A

test(crypto): add unit test for `copy` and `insertSubTree` method  in AccQueue

---

cli/ts/commands/proveOnChain.ts
contracts/tasks/helpers/Prover.ts
contracts/tasks/helpers/types.ts
contracts/tasks/runner/prove.ts

fix `vkRegsitryContract` -> `vkRegistryContract` typo
N/A
N/A

fix(cli): fix cli vkRegistry typo

---

integrationTests/package.json
pnpm-lock.yaml

Add missing typescript dependency for integration tests package
N/A
N/A

fix(build): add missing typescript dependency for integration tests package

---

cli/ts/commands/genProofs.ts
contracts/contracts/Poll.sol
contracts/deploy-config-example.json
contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/helpers/types.ts
contracts/tasks/runner/prove.ts

Now you don't need to specify start and end blocks. By default start block is a first signup event block; end - last merge aq event block. 
MACI rpgf feedback discussion

chore: use non-zero start and end blocks for proof generation

---

cli/tests/e2e/e2e.test.ts
cli/ts/commands/genLocalState.ts

Introduce the new logic to determine first and last block for events fetching into the genLocalState command

chore(genlocalstate): add start block calculation on genLocalState cli command

---

cli/testScript.sh
integrationTests/ts/__tests__/utils/constants.ts
website/versioned_docs/version-v1.x/cli.md

Update maci keys in docs to reflect new serialization format (zk-kit update)

docs(keys): update maci keys in docs and scripts

---

cli/ts/commands/genLocalState.ts
cli/ts/commands/genProofs.ts
cli/ts/commands/signup.ts
cli/ts/utils/interfaces.ts
contracts/tasks/helpers/ProofGenerator.ts

Add start block for `isRegistered` cli sdk method and for deployment event parsing to prevent rate limit errors

feat(cli): add start block for signup event parsing

---

cli/testScript.sh

- remove `-se` flag for `deployPoll` cmd in `testScript.sh`

fix: remove -se in test script

---

cli/ts/commands/deployPoll.ts
cli/ts/commands/proveOnChain.ts
contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/contracts/MessageProcessorFactory.sol
contracts/contracts/Tally.sol
contracts/contracts/TallyFactory.sol
contracts/contracts/VkRegistry.sol
contracts/contracts/interfaces/IMPFactory.sol
contracts/contracts/interfaces/ITallyFactory.sol
contracts/contracts/interfaces/IVkRegistry.sol
contracts/contracts/utilities/DomainObjs.sol
contracts/tasks/deploy/poll/01-poll.ts
contracts/tasks/helpers/Prover.ts
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Poll.test.ts
contracts/tests/Tally.test.ts
contracts/tests/TallyNonQv.test.ts
integrationTests/ts/__tests__/maci-keys.test.ts

feat: use mode instead of flag for voting option

---

website/versioned_docs/version-v1.2/integrating.md
website/versioned_docs/version-v1.3_alpha/integrating.md

Added a note about running non QV on Integratin page

docs(add note about non qv on integrating): added a note about running non QV on Integrating page

---

.github/workflows/coordinator-build.yml
coordinator/.eslintrc.js
coordinator/hardhat.config.ts
coordinator/nest-cli.json
coordinator/package.json
coordinator/tests/app.test.ts
coordinator/ts/app.controller.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/app.module.ts
coordinator/ts/app.service.ts
coordinator/ts/main.ts
coordinator/tsconfig.build.json
coordinator/tsconfig.json
lerna.json
pnpm-lock.yaml
pnpm-workspace.yaml

N/A
Closes https://github.com/privacy-scaling-explorations/maci-rpgf/issues/57

feat(coordinator): add coordinator service boilerplate

---

website/blog/2024-04-10-roadmap-q2.md
website/src/pages/roadmap.md

Add Q2 MACI roadmap blog post
https://github.com/privacy-scaling-explorations/maci/discussions/859

docs: add Q2 roadmap post

---

contracts/contracts/gatekeepers/EASGatekeeper.sol
contracts/contracts/mocks/MockEAS.sol
contracts/tests/EASGatekeeper.test.ts

Mock gatekeeper tests vs using forked environment
Fix: #1409

test(eas): mock gatekeeper tests

---

contracts/contracts/mocks/MockEAS.sol
contracts/contracts/mocks/MockHatsProtocol.sol
contracts/tests/HatsGatekeeper.test.ts

Mock hats gatekeepers
re: #1409

test(hats): mock hats gatekeeper tests

---

contracts/.env.example
contracts/tasks/helpers/constants.ts

chore(contracts): move away from infura key to full rpc url

---

cli/ts/sdk/index.ts
contracts/tasks/helpers/ContractStorage.ts
contracts/tasks/helpers/Deployment.ts
contracts/tsconfig.build.json
contracts/tsconfig.json

N/A
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/64

feat(contracts): add new adapter for lowdb to support browser env 

---

contracts/contracts/MACI.sol
contracts/contracts/Poll.sol
contracts/contracts/crypto/BabyJubJub.sol
contracts/tests/MACI.test.ts
contracts/tests/Poll.test.ts
crypto/ts/index.ts
domainobjs/ts/__tests__/keypair.test.ts
domainobjs/ts/__tests__/publicKey.test.ts
domainobjs/ts/commands/PCommand.ts
domainobjs/ts/privateKey.ts
domainobjs/ts/publicKey.ts

Ensure MACI keys are correctly validated to be a point on the babyjujub curve

fix: do not accept invalid maci keys

---

circuits/circom/trees/incrementalMerkleTree.circom
circuits/circom/trees/incrementalQuinaryTree.circom

Simplify the generate path indices templates (binary and quinary)
fix #1420

refactor(circuits): simplify generatePathIndices templates

---

.github/workflows/coordinator-build.yml
contracts/ts/index.ts
coordinator/.env.example
coordinator/.gitignore
coordinator/package.json
coordinator/scripts/generateKeypair.ts
coordinator/ts/crypto/__tests__/crypto.service.test.ts
coordinator/ts/crypto/crypto.service.ts
coordinator/ts/main.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts
coordinator/ts/proof/types.ts
coordinator/tsconfig.build.json
coordinator/tsconfig.json
pnpm-lock.yaml

Auth-z, controller and e2e tests are not implemented yet, but will be added in next PRs.
Current PR has atomic change for maci-coordinator package and doesn't affect anything.
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/60

feat(coordinator): add crypto and proof generation services

---

.github/workflows/coordinator-build.yml
.github/workflows/nightly.yml
.github/workflows/reusable-e2e.yml
contracts/scripts/compileSol.ts
contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/runner/prove.ts
coordinator/.env.example
coordinator/.gitignore
coordinator/hardhat.config.ts
coordinator/package.json
coordinator/scripts/downloadZkeys.ts
coordinator/tests/app.test.ts
coordinator/ts/app.controller.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/app.module.ts
coordinator/ts/app.service.ts
coordinator/ts/jest/transform.js
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts
coordinator/ts/proof/types.ts
package.json
pnpm-lock.yaml
website/versioned_docs/version-v1.3_alpha/circuits.md
website/versioned_docs/version-v1.3_alpha/installation.md
website/versioned_docs/version-v1.3_alpha/testing.md
website/versioned_docs/version-v1.3_alpha/troubleshooting.md

Need to add guard and input checks
Related to https://github.com/privacy-scaling-explorations/maci-rpgf/issues/60

feat(coordinator): add coordinator controller

---

contracts/contracts/gatekeepers/EASGatekeeper.sol
contracts/contracts/gatekeepers/GitcoinPassportGatekeeper.sol
contracts/contracts/interfaces/IGitcoinPassportDecoder.sol
contracts/contracts/mocks/MockGitcoinPassportDecoder.sol
contracts/contracts/mocks/MockHatsProtocol.sol
contracts/deploy-config-example.json
contracts/package.json
contracts/tasks/deploy/maci/02-gatekeepers.ts
contracts/tasks/deploy/maci/09-maci.ts
contracts/tasks/helpers/types.ts
contracts/tests/EASGatekeeper.test.ts
contracts/tests/GitcoinPassportGatekeeper.test.ts
contracts/tests/HatsGatekeeper.test.ts
contracts/ts/deploy.ts
contracts/ts/index.ts

Implement a gatekeeper that uses a gitcoin passport score as criteria to signup to MACI. 
fix #1444

feat(gatekeepers): implement a gitcoin passport gatekeeper

---

contracts/tasks/deploy/maci/06-pollFactory.ts
contracts/tasks/deploy/maci/07-messageProcessorFactory.ts
contracts/tasks/deploy/maci/08-tallyFactory.ts
contracts/tasks/deploy/maci/09-maci.ts
contracts/tasks/helpers/Deployment.ts
contracts/tasks/helpers/types.ts
contracts/ts/deploy.ts

Currently, if using `Deployment` helper to deploy contracts with linked libraries, it would check if there is hardhat environment running or not. Make this optional by accepting `signer` as input argument, for frontend to call and use.

feat: add signer as input for deployContractWithLinkedLibraries

---

cli/ts/commands/genLocalState.ts
cli/ts/commands/genProofs.ts
cli/ts/commands/mergeMessages.ts
cli/ts/commands/mergeSignups.ts
cli/ts/commands/poll.ts
contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/contracts/MessageProcessorFactory.sol
contracts/contracts/Poll.sol
contracts/contracts/PollFactory.sol
contracts/contracts/Tally.sol
contracts/contracts/TallyFactory.sol
contracts/contracts/interfaces/IPoll.sol
contracts/contracts/interfaces/IPollFactory.sol
contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/helpers/TreeMerger.ts
contracts/tasks/runner/merge.ts
contracts/tasks/runner/prove.ts
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Poll.test.ts
contracts/tests/PollFactory.test.ts
contracts/tests/Tally.test.ts
contracts/tests/TallyNonQv.test.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts
package.json

Ensure functions/events/variables/test descriptions reflect the latest code changes optimize contracts and remove unnecessary logic

refactor: general cleanup, variables/events/functions renaming

---

.github/workflows/coordinator-build.yml
coordinator/.env.example
coordinator/hardhat.config.ts
coordinator/package.json
coordinator/tests/app.test.ts
coordinator/ts/app.controller.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/auth/AccountSignatureGuard.service.ts
coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
coordinator/ts/main.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/dto.ts
coordinator/ts/proof/proof.service.ts
coordinator/ts/proof/types.ts
pnpm-lock.yaml

N/A
Closes https://github.com/privacy-scaling-explorations/maci-rpgf/issues/60

feat(coordinator): auth-z and validation

---

cli/ts/utils/storage.ts

remove duplicate words in commet

chore: remove duplicate words

---

coordinator/.env.example
coordinator/tests/app.test.ts
coordinator/ts/app.controller.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/common/errors.ts
coordinator/ts/common/index.ts
coordinator/ts/crypto/__tests__/crypto.service.test.ts
coordinator/ts/crypto/crypto.service.ts
coordinator/ts/main.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts

feat(coordinator): add generic errors

---

package.json

Do not run maci-coordinator tests together with unit tests on nightly CI as they require extra steps
fix #1414

fix(nightly): do not run maci-coordinator tests from root on nightly

---

cli/ts/index.ts

The problem is the `<useQuadraticVoting>` argument is missing for the cli commands after `-uq`, that's why `cmdObj.useQuadraticVoting` would always be false.
close #1465

fix: add uq argument in cli/index

---

.github/workflows/config/typos.toml
.github/workflows/typos.yml
circuits/circom/core/non-qv/processMessages.circom
circuits/circom/core/qv/processMessages.circom
circuits/circom/utils/non-qv/stateLeafAndBallotTransformer.circom
circuits/circom/utils/qv/stateLeafAndBallotTransformer.circom
cli/ts/commands/genProofs.ts
contracts/tasks/runner/prove.ts
contracts/tests/utils.ts
contracts/ts/types.ts
domainobjs/ts/commands/PCommand.ts
integrationTests/ts/__tests__/utils/utils.ts
website/versioned_docs/version-v1.2/typedoc/domainobjs/classes/PCommand.md

- add automatic typo detection in CI
- Blocks all CHANGELOG typos checks, although there are indeed some typos in it, it does not affect the readability of the main code.
- If we need to check CHANGELOG, we need to add further extend-words eg.`ede`
```
error: `ede` should be `edge`
--> ./domainobjs/CHANGELOG.md:56:64
|
56 | * **deps-dev:** bump @types/node from 20.11.2 to 20.11.5 ([7698ede](https://github.com/privacy-scaling-explorations/maci/commit/7698edef2b95bc017e54c1fc0d796ccc9da3de85))
|                                                                ^^^
|
error: `polution` should be `pollution`
--> ./crypto/CHANGELOG.md:27:46
|
27 | * **crypto:** get rid of potential prototype polution ([9b8a97c](https://github.com/privacy-scaling-explorations/maci/commit/9b8a97cc9661e0ee6f535cdcab19 …
```

ci: add typo detection tool

---

.github/workflows/config/typos.toml
.github/workflows/typos.yml
circuits/circom/core/non-qv/processMessages.circom
circuits/circom/core/qv/processMessages.circom
website/blog/2023-01-18-maci-v1.1.1.md
website/blog/2024-04-10-roadmap-q2.md
website/versioned_docs/version-v0.x/state-root-transition-circuit.md

Fix typos workflow by adding exceptions and fixing mistakes left.

fix: typos workflow

---

cli/ts/sdk/index.ts
contracts/tasks/helpers/Deployment.ts
contracts/tasks/helpers/types.ts

- export pubkey for frontend to generate unserialized key to deploy a poll
- update description of deployment.deployContract and deployment.deployContractWithLinkedLibraries

feat: export pubkey and update description of deployment

---

contracts/tasks/helpers/Deployment.ts
contracts/tasks/helpers/types.ts

Allow the `Deployment` helper to call `getContract` without hardhat environment.

feat: allow getContract without hardhat environment

---

website/versioned_docs/version-v2.0_alpha/developers-references/integrating.md
website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md
website/versioned_docs/version-v2.0_alpha/quick-start/poll-finalization.md
website/versioned_docs/version-v2.0_alpha/quick-start/troubleshooting.md

Separate deployment docs, add poll finalization and keep up to date.

docs: separate deployment docs and keep up to date

---

circuits/circom/core/non-qv/processMessages.circom
circuits/circom/core/qv/processMessages.circom
contracts/contracts/Poll.sol
contracts/tasks/helpers/types.ts

chore(cleanup): remove references to topup

---

website/blog/2024-04-10-roadmap-q2.md
website/versioned_docs/version-v2.0_alpha/core-concepts/_category_.json
website/versioned_docs/version-v2.0_alpha/core-concepts/ballot.md
website/versioned_docs/version-v2.0_alpha/core-concepts/key-change.md
website/versioned_docs/version-v2.0_alpha/core-concepts/maci-messages.md
website/versioned_docs/version-v2.0_alpha/core-concepts/poll-types.md
website/versioned_docs/version-v2.0_alpha/core-concepts/state-leaf.md
website/versioned_docs/version-v2.0_alpha/overview/resources.md
website/versioned_docs/version-v2.0_alpha/overview/workflow.md
website/versioned_docs/version-v2.0_alpha/quick-start/_category_.json
website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md

Remove redundant MACI word from everywhere,  and organise order

docs: cleanup docs and re organize order

---

contracts/tasks/helpers/ContractStorage.ts
contracts/tasks/helpers/types.ts

want to: get deployment transaction information
how?
1. store transaction hash of deployment transaction in the ContractStorage.
2. add a function `getDeploymentTxHash` for user to get the transaction hash to get the complete information of that transaction.
https://github.com/privacy-scaling-explorations/maci-rpgf/issues/115

feat: store deployment transaction hash

---

.github/scripts/build.sh
.github/scripts/deploy.sh
.github/workflows/coordinator-deploy.yml
coordinator/apps/Dockerfile

With this PR, a new GH Actions workflow is introduced to enable coordinator auto deployment to a dedicated AWS Fargate cluster, each time there is a push to the dev branch.
The workflow execution triggers the following events:
- Authentication against AWS using short lived credentials to specific cloud resources
- Docker image build
- Image upload to AWS Repository (ECR)
- Update ECS cluster deployment with the latest image
The endpoint can be reached at: http://maci-coordinator.pse.dev:8545

feat: GH Actions workflow to support coordinator auto-deployment to Fargate

---

coordinator/tests/app.test.ts
coordinator/ts/app.controller.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/app.module.ts
coordinator/ts/auth/AccountSignatureGuard.service.ts
coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
coordinator/ts/common/errors.ts
coordinator/ts/crypto/__tests__/crypto.service.test.ts
coordinator/ts/crypto/crypto.module.ts
coordinator/ts/crypto/crypto.service.ts
coordinator/ts/file/__tests__/file.service.test.ts
coordinator/ts/file/file.module.ts
coordinator/ts/file/file.service.ts
coordinator/ts/file/types.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts

N/A
Closes https://github.com/privacy-scaling-explorations/maci-rpgf/issues/58

feat: coordinator public key method

---

website/versioned_docs/version-v2.0_alpha/quick-start/poll-finalization.md

Move contract tasks finalization instructions before maci-cli and ensure the --use-quadratic-voting flag is highlighted

docs(finalization): ensure the quadratic voting flag is highlighted

---

circuits/circom/utils/non-qv/messageValidator.circom
circuits/circom/utils/qv/messageValidator.circom

Ensure we do the correct validation on messages, by checking that the index is < total signups (not <=)

fix(circuits): ensure we check index < numSignups

---

website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md
website/versioned_docs/version-v2.0_alpha/quick-start/poll-finalization.md

Improved quickstart and gatekeepers

docs(quickstart-and-gatekeepers): improved quickstart and gatekeepers

---

subgraph/schemas/schema.v1.graphql
subgraph/src/maci.ts
subgraph/src/poll.ts
subgraph/src/utils/constants.ts
subgraph/src/utils/entity.ts
subgraph/tests/maci/maci.test.ts
subgraph/tests/poll/poll.test.ts

feat(subgraph): optimize subgraph schema (maci)

---

core/ts/__tests__/e2e.test.ts

test(core): remove msgTree

---

website/versioned_docs/version-v1.2/contracts.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md

Describe how to get the actual number of "real" users signed up for a maci poll.
fix #962

docs: ensure that it's clear that num signups account for empty leaf

---

website/versioned_docs/version-v2.0_alpha/contributing/_category_.json
website/versioned_docs/version-v2.0_alpha/processes/_category_.json
website/versioned_docs/version-v2.0_alpha/project-ideas/_category_.json
website/versioned_docs/version-v2.0_alpha/security/_category_.json
website/versioned_docs/version-v2.0_alpha/testing/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/governance/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/governance/governance.md
website/versioned_docs/version-v2.0_alpha/use-cases/local-elections/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/local-elections/local-elections.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/public-goods.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/apply.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/case-studies.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/faq.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/how-it-works.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/registration-approaches.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/quadratic-funding/what-is-quadratic-funding.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/_category_.json
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/case-studies.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/how-it-works.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/registration-approaches.md
website/versioned_docs/version-v2.0_alpha/use-cases/public-goods-funding/retroactive-public-goods-funding/what-is-retroactive-public-goods-funding.md

Port over qf super site content and bootstrap maci use cases entry.
fix #1569 
fix #1568

docs(use-cases): add use cases entry in the doc website and start adding content

---

website/versioned_docs/version-v2.0_alpha/developers-references/zk-snark-circuits/setup.md
website/versioned_docs/version-v2.0_alpha/quick-start/deployment.md
website/versioned_docs/version-v2.0_alpha/quick-start/installation.md

Ensure it is clear how to configure the circuits and build the project to support different state tree depths.

docs: clarify circuits parameters

---

contracts/testScriptLocalhost.sh
coordinator/.env.example
coordinator/ts/main.ts

- add `COORDINATOR_PORT` as one of the environment variable input, it's fixed to 3000 originally
- remove `process-zkey`, `process-wasm`, `tally-zkey`, `tally-wasm` as `prove:[network]` command parameters in the `testScriptLocalhost.sh` in contracts package.

chore: add port as env variable and remove redundant param in testScript

---

coordinator/hardhat.config.js

Currently, when I'm running on my localhost, the `signer` cannot be found, so the accounts should be provided.
⬇️ This is the problem I encountered.
https://github.com/privacy-scaling-explorations/maci-rpgf/pull/167

chore: add mnemonic to hardhat config file

---

contracts/contracts/gatekeepers/SemaphoreGatekeeper.sol
contracts/contracts/interfaces/ISemaphore.sol
contracts/contracts/mocks/MockSemaphore.sol
contracts/package.json
contracts/tests/SemaphoreGatekeeper.test.ts

Implement a MACI gatekeeper that uses semaphore to gatekeep access to group members only

feat(contracts): implement semaphore gatekeeper

---

website/blog/2024-06-21-deciphering-maci.md

Add Deciphering MACI blog post by Vee.

docs(blog): add deciphering maci post

---

website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/DeployedContracts.md

Add documentation entry to store addresses of deployed smart contracts

docs: add documentation entry for already deployed smart contracts

---

cli/ts/commands/mergeMessages.ts
cli/ts/commands/mergeSignups.ts
cli/ts/commands/proveOnChain.ts
cli/ts/commands/setVerifyingKeys.ts

Since the `mergeSignups` and `mergeMessages` import `MACIFactory` from `maci-contracts`, so the frontend would accidentally import `hardhat` packages, which caused the frontend error.
https://github.com/privacy-scaling-explorations/maci-rpgf/pull/167

fix: export typechain instead of contract

---

cli/ts/commands/extractVkToFile.ts
cli/ts/commands/mergeMessages.ts
cli/ts/commands/mergeSignups.ts

The `prompt` package cannot be called from the frontend too, so instead of importing functions from `cli/utils` (which imports functions from `cli/utils/index.ts`), need to import from different files.
https://github.com/privacy-scaling-explorations/maci-rpgf/pull/167

fix: avoid export prompt in cli/sdk

---

website/docusaurus.config.ts
website/src/pages/projects.md

Add projects page to the doc website

docs: add projects page to the doc website

---

contracts/contracts/Poll.sol
contracts/contracts/Tally.sol

Remove unused code from Tally contract and optimize memory read for Poll contract.
N/A

refactor: optimize poll and tally contracts variables

---

contracts/contracts/MACI.sol
contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/helpers/types.ts
contracts/tasks/runner/prove.ts
coordinator/ts/proof/proof.service.ts
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md

~{number of batches} times less time for proof generation
Closes #1615

feat: proof parallelization

---

contracts/tests/SemaphoreGatekeeper.test.ts
contracts/ts/deploy.ts
contracts/ts/index.ts

This PR add `deploySemaphoreGatekeeper()` function to `contracts` package.
N/A

feat(contracts): add `deploySemaphoreGatekeeper()`

---

contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/helpers/types.ts
contracts/ts/index.ts
coordinator/README.md
coordinator/package.json
coordinator/tests/app.test.ts
coordinator/ts/app.controller.ts
coordinator/ts/app.module.ts
coordinator/ts/auth/AccountSignatureGuard.service.ts
coordinator/ts/auth/__tests__/AccountSignatureGuard.test.ts
coordinator/ts/events/__tests__/events.gateway.test.ts
coordinator/ts/events/events.gateway.ts
coordinator/ts/events/events.module.ts
coordinator/ts/events/types.ts
coordinator/ts/proof/proof.service.ts
pnpm-lock.yaml

feat(coordinator): add websockets support

---

cli/ts/commands/signup.ts
cli/ts/sdk/index.ts
cli/ts/utils/index.ts
cli/ts/utils/interfaces.ts

Add utility function to get semaphore contract address and group id from the gatekeeper.

chore: add function to get semaphore gatekeeper details

---

cli/ts/sdk/index.ts

export directly from utils/interfaces to avoid importing unneded modules

fix: export value from utils/interfaces vs utils

---

website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/AccQueue.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Gatekeepers.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MACI.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/MessageProcessor.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Params.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Poll.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/PollFactory.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/Tally.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VkRegistry.md
website/versioned_docs/version-v2.0_alpha/developers-references/smart-contracts/VoiceCreditProxy.md

Add links to code inside the contracts documentation
fix #1253

docs: add links to the smart contracts code in the docs

---

contracts/tasks/deploy/maci/08-maci.ts

Ensure we set the maci contract on the gatekeeper

fix(contracts): ensure we call setMaci when deploying semaphoreGatekeeper

---

cli/ts/commands/index.ts
cli/ts/commands/signup.ts
cli/ts/sdk/index.ts
cli/ts/utils/index.ts
cli/ts/utils/interfaces.ts

Add a function to get zupass gatekeeper data

feat(sdk): add function to get zupass gatekeeper data

---

circuits/circom/core/non-qv/processMessages.circom
circuits/circom/core/qv/processMessages.circom
circuits/circom/utils/non-qv/messageValidator.circom
circuits/circom/utils/non-qv/stateLeafAndBallotTransformer.circom
circuits/circom/utils/qv/messageValidator.circom
circuits/circom/utils/qv/stateLeafAndBallotTransformer.circom
circuits/ts/__tests__/MessageValidator.test.ts
circuits/ts/__tests__/StateLeafAndBallotTransformer.test.ts

Remove duplicate constraints on circuits by re-using signals and removing unnecessary checks.
fix #305

refactor(circuits): remove duplicate constraints

---

website/versioned_docs/version-v2.0_alpha/contributing/contributing.md

Extend contribution guidelines

docs: extend contribution guidelines

---

.github/workflows/hardhat-tasks.yml
contracts/deploy-config-example.json
contracts/tasks/deploy/maci/08-maci.ts

This PR fixes the issue where the hardhat task in `maci-contracts` is unable to deploy the MACI contract due to it being outdated with the changes introduced in #1695 (see 'Additional Notes' below for the detailed error log).
Additionally, I added a CI job that executes the hardhat task so we can detect deployment errors earlier (see [this detaction example](https://github.com/baumstern/maci/actions/runs/10117090816/job/27981350744) of the new CI job).
the error message: `ERROR: TypeError: Do not know how to serialize a BigInt`
cause of the error: `emptyBallotRoots` is `bigint[]` but `JSON.stringify()` can not handle `bigint[]` type
solution: casting `bigint[]` into `string[]`
detailed error log:
```
$ pnpm deploy:localhost
....
============================================================= …
```

fix(contracts): fix a deploy error in the hardhat task

---

contracts/hardhat.config.ts
contracts/tasks/helpers/constants.ts

This PR fixes the issue where deploying a Vk Registry to the Sepolia network using the Hardhat task is unsuccessful. The problem was due to the `gasPrice` being hardcoded to 1, which caused deployment failures. By configuring `gasPrice` to [`auto`](https://hardhat.org/hardhat-runner/docs/config#json-rpc-based-networks) it will automatically estimate a suitable gas price based on current network congestion.
(I tried five times with current configuration, but the CLI process kept hanging indefinitely. Setting the `gasPrice` to `auto` resolved the issue.)

fix(contracts): ensure `gasPrice` has sufficient value

---

coordinator/.env.example
coordinator/package.json
pnpm-lock.yaml
subgraph/package.json
subgraph/tsconfig.build.json

Allow maci-subgraph to be published on npm and import inside maci-coordinator

chore(subgraph): configure maci-subgraph to be a public npm package

---

cli/tests/ceremony-params/ceremonyParams.test.ts
cli/tests/constants.ts
cli/tests/e2e/e2e.nonQv.test.ts
cli/tests/e2e/e2e.test.ts
cli/ts/commands/genLocalState.ts
cli/ts/commands/genProofs.ts
cli/ts/commands/mergeMessages.ts
cli/ts/commands/mergeSignups.ts
cli/ts/commands/poll.ts
cli/ts/commands/proveOnChain.ts
cli/ts/commands/publish.ts
cli/ts/commands/verify.ts
cli/ts/index.ts
cli/ts/utils/interfaces.ts
contracts/contracts/MACI.sol
contracts/tasks/runner/merge.ts
contracts/tasks/runner/prove.ts
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Poll.test.ts
contracts/tests/Tally.test.ts
contracts/tests/TallyNonQv.test.ts
coordinator/ts/proof/__tests__/proof.service.test.ts
coordinator/ts/proof/proof.service.ts
integrationTests/ts/__tests__/integration.test.ts
integrationTests/ts/__tests__/maci-keys.test.ts
subgraph/package.json
subgraph/tsconfig.build.json

Changed the polls mapping to return the PollContracts struct instead of the poll address, it will now return the message processor address, tally contract address and poll contract address, when we will fetch the poll from the polls mapping and the getPoll function.

feat(contracts): added message processor and tally addresses to the maci contract

---

contracts/tests/EASGatekeeper.test.ts
contracts/tests/GitcoinPassportGatekeeper.test.ts
contracts/tests/MACI.test.ts
contracts/tests/MessageProcessor.test.ts
contracts/tests/Poll.test.ts
contracts/tests/Tally.test.ts
contracts/tests/TallyNonQv.test.ts
contracts/tests/Verifier.test.ts
contracts/tests/VkRegistry.test.ts
contracts/tests/ZupassGatekeeper.test.ts

Cleanup contract tests by removing unnecessary code.

test(contracts): cleanup contracts tests

---

cli/ts/commands/deployPoll.ts
contracts/contracts/MACI.sol
contracts/contracts/MessageProcessor.sol
contracts/tasks/deploy/poll/01-poll.ts
contracts/ts/genMaciState.ts
subgraph/src/maci.ts
subgraph/templates/subgraph.template.yaml
subgraph/tests/common.ts
subgraph/tests/maci/maci.test.ts
subgraph/tests/maci/utils.ts
subgraph/tests/poll/poll.test.ts

Do not return poll/mp/tally addresses as they are already saved to state
fix #1724

refactor(contracts): do not return contract addresses on poll deploy

---

.github/scripts/downloadZkeys.ts
circuits/ts/compile.ts
circuits/ts/genZkeys.ts
circuits/ts/proofs.ts
cli/tests/ceremony-params/ceremonyParams.test.ts
cli/tests/constants.ts
cli/tests/e2e/e2e.nonQv.test.ts
cli/tests/e2e/e2e.test.ts
cli/tests/e2e/keyChange.test.ts
cli/tests/unit/poll.test.ts
cli/tests/utils.ts
cli/ts/commands/checkVerifyingKeys.ts
cli/ts/commands/deploy.ts
cli/ts/commands/deployPoll.ts
cli/ts/commands/deployVkRegistry.ts
cli/ts/commands/genLocalState.ts
cli/ts/commands/genProofs.ts
cli/ts/commands/mergeMessages.ts
cli/ts/commands/mergeSignups.ts
cli/ts/commands/proveOnChain.ts
cli/ts/commands/setVerifyingKeys.ts
cli/ts/index.ts
cli/ts/utils/storage.ts
contracts/tasks/helpers/ProofGenerator.ts
contracts/tasks/runner/prove.ts
integrationTests/ts/__tests__/integration.test.ts

Use async fs instead of sync version to prevent race conditions for tests
N/A

chore: use async fs instead of sync version

---

packages/circuits/ts/compile.ts
packages/circuits/ts/proofs.ts

Use dynamic imports for promisify
N/A
N/A

fix(circuits): use dynamic imports for promisify

---

apps/website/blog/2024-08-10-maci-v2.md

docs(blog): fix audit link in v2 blog

---

packages/cli/ts/commands/signup.ts
packages/cli/ts/sdk/index.ts
packages/cli/ts/utils/index.ts
packages/cli/ts/utils/interfaces.ts

Add a function to get hats gatekeeper data for a client

feat(sdk): get hats gatekeeper data

---

packages/contracts/tasks/deploy/poll/01-poll.ts

Ensure we can verify the poll contract by storing all constructor args

fix: poll verification

---

apps/website/src/css/card.module.css

Add dark mode styling for `/blogs` page, refer to the color set of maci-platform design.

feat(website): add darkmode for blog cards

---

apps/website/versioned_docs/version-v2.x/developers-references/smart-contracts/DeployedContracts.md
apps/website/versioned_docs/version-v2.x/developers-references/smart-contracts/SupportedNetworks.md
packages/contracts/default-deployed-contracts.json
packages/contracts/hardhat.config.ts
packages/contracts/package.json
packages/contracts/tasks/helpers/benchmarks.ts
packages/contracts/tasks/runner/benchmarks.ts

Deploy contracts to main L2 networks. Add a benchmark task for message batch costs and size. Store all new addresses for re-use.
fix #1689

chore(contracts): deploy contracts to L2s, store addresses and benchmark message batch size

---

apps/website/docusaurus.config.ts
apps/website/package.json
pnpm-lock.yaml

Put `matomo` plugin in the website to track usage.
Use a plugin here, because I think it's a better way and more readable(?). But if in any case it's not working, we could put the script in the `docusaurus.config.ts` file by adding `headTags`.

feat: add matomo plugin

---

packages/contracts/tasks/helpers/Prover.ts
packages/contracts/tasks/helpers/constants.ts

Ensure we use the correct tree arity values

fix: use correct tree arity and import from maci-core

---

packages/cli/ts/commands/signup.ts
packages/cli/ts/utils/interfaces.ts

Return the voice credits when signing up to avoid having to fetch them separately later

feat: return voice credits on signup

---

apps/website/versioned_docs/version-v2.x/security/trusted-setup.md

Update docs to inform about trusted setup and that 1.2 production keys cannot be used with v2. 
re: #1717

docs: update trusted setup docs

---

packages/contracts/tests/EASGatekeeper.test.ts
packages/contracts/tests/GitcoinPassportGatekeeper.test.ts
packages/contracts/tests/HatsGatekeeper.test.ts
packages/contracts/tests/MACI.test.ts
packages/contracts/tests/MessageProcessor.test.ts
packages/contracts/tests/Poll.test.ts
packages/contracts/tests/SemaphoreGatekeeper.test.ts
packages/contracts/tests/SignUpGatekeeper.test.ts
packages/contracts/tests/Tally.test.ts
packages/contracts/tests/TallyNonQv.test.ts
packages/contracts/tests/ZupassGatekeeper.test.ts
packages/contracts/tests/utils.ts
packages/contracts/ts/deploy.ts
packages/contracts/ts/index.ts
packages/contracts/ts/types.ts

Refactoring for deploying test contracts
N/A

refactor(contracts): use custom factories for maci test deploys

---

packages/contracts/tasks/helpers/ContractStorage.ts

Add storage path as argument to ContractStorage and add function to retrieve deployment arguments

feat(storage): add storage path and function to get deployment args

---

packages/contracts/tasks/helpers/types.ts
packages/contracts/ts/index.ts

Add enum to keep track of gatekeepers and voice credit proxies

chore: add enum for gatekeepers and voice credits proxy

---

CHANGELOG.md
apps/subgraph/CHANGELOG.md
apps/subgraph/package.json
apps/website/CHANGELOG.md
apps/website/package.json
lerna.json
package.json
packages/circuits/CHANGELOG.md
packages/circuits/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/contracts/CHANGELOG.md
packages/contracts/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/crypto/CHANGELOG.md
packages/crypto/package.json
packages/domainobjs/CHANGELOG.md
packages/domainobjs/package.json
packages/integrationTests/CHANGELOG.md
packages/integrationTests/package.json
pnpm-lock.yaml

chore(release): publish 2.2.0

---

packages/contracts/ts/index.ts

Remove poseidon contract creation from exports of `maci-contracts`
N/A
N/A

fix(contracts): remove poseidon builders from exports

---

packages/contracts/tasks/helpers/ContractStorage.ts
packages/contracts/tasks/helpers/Deployment.ts
packages/contracts/tasks/helpers/types.ts

Type updates for storage and deployment helpers to allow use user defined contracts config.
N/A

chore(contracts): extend ids for contract storage and deployment

---

apps/website/docusaurus.config.ts
apps/website/versioned_docs/version-v1.2/introduction.md

This PR removes the version banner in v1.2
It also adds an info message in the `introduction.md`
fix #1471

chore(docs): remove version banner in v1.2

---

packages/contracts/tasks/helpers/Deployment.ts
packages/contracts/tasks/helpers/benchmarks.ts
packages/contracts/tasks/runner/benchmarks.ts

Make benchmark automatically change message tree depth 
Do not use estimate gas as it provides unreliable results (for instance on op sepolia says 100 would work but doesn't actually work)

chore: update message tree depth programmatically in benchmarks

---

.github/workflows/nightly-ceremony.yml
packages/circuits/ts/__tests__/CeremonyParams.test.ts
packages/cli/tests/ceremony-params/ceremonyParams.test.ts
packages/cli/tests/constants.ts

Update tests to work with latest release

test(ceremony): update ceremony tests to work with v2 params and keys

---

packages/circuits/ts/proofs.ts
packages/contracts/tasks/helpers/ProofGenerator.ts

There currently is a hanging issue with generating proofs within the hardhat tasks due to the different promises opening and closing handles to the same curve (reference: https://github.com/iden3/snarkjs/issues/152)
Also, do not extract Vk every time but only once when generating proofs for multiple batches

fix: do not cleanup thread all the time while doing parallel proof gen

---

packages/cli/tests/constants.ts

Ensure we use the right paths in the ceremony params tests

fix: ensure nightly workflow use correct paths

---

packages/contracts/deploy-config-example.json
packages/contracts/tasks/deploy/maci/02-gatekeepers.ts
packages/contracts/tasks/helpers/types.ts

Added Merkleroot Gatekeeper deploy scripts and example

feat(merkleroot-gatekeeper): added deploy scripts and config

---

apps/website/versioned_docs/version-v2.x/core-concepts/merkle-trees.md

This PR updates de github link for the `AccQueue.sol` contract in the documentation. The current link does not work
None
None

chore(docs): update link for AccQueue contract

---

packages/cli/ts/commands/signup.ts
packages/cli/ts/sdk/index.ts
packages/cli/ts/utils/index.ts
packages/cli/ts/utils/interfaces.ts

Added merkleproof gatekeeper to signup script and utils

feat(scripts): added merkleproof gatekeeper to signup script and utils

---

apps/website/versioned_docs/version-v2.x/developers-references/maci-wrapper/QuickStartGuide.md

Updated to v2 MACI Wrapper guide

docs(maci-wrapper-guide): updated maci wrapper guide

---

CHANGELOG.md
apps/subgraph/CHANGELOG.md
apps/subgraph/package.json
apps/website/CHANGELOG.md
apps/website/package.json
lerna.json
package.json
packages/circuits/CHANGELOG.md
packages/circuits/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/contracts/CHANGELOG.md
packages/contracts/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/crypto/CHANGELOG.md
packages/crypto/package.json
packages/domainobjs/CHANGELOG.md
packages/domainobjs/package.json
packages/integrationTests/CHANGELOG.md
packages/integrationTests/package.json
pnpm-lock.yaml

Release new feature version for packages
N/A
N/A

chore(release): publish 2.4.0

---

packages/cli/tests/constants.ts
packages/cli/ts/commands/proveOnChain.ts
packages/cli/ts/index.ts
packages/cli/ts/utils/interfaces.ts
packages/contracts/contracts/Tally.sol
packages/contracts/tasks/helpers/Prover.ts
packages/contracts/tasks/runner/prove.ts
packages/contracts/tests/Tally.test.ts
packages/integrationTests/ts/__tests__/integration.test.ts

feat(contracts): add tally results

---

packages/contracts/contracts/Tally.sol
packages/contracts/package.json
packages/contracts/tests/Tally.test.ts
pnpm-lock.yaml

Found an issue that allows to write the same tally results but `totalTallyResults` will be incremented.
N/A

fix(contracts): prevent adding additional tally results

---

packages/contracts/contracts/gatekeepers/AnonAadhaarGatekeeper.sol
packages/contracts/contracts/interfaces/IAnonAadhaar.sol
packages/contracts/contracts/mocks/MockAnonAadhaar.sol
packages/contracts/package.json
packages/contracts/tests/AnonAadhaarGatekeeper.test.ts
packages/contracts/ts/deploy.ts

Implement a MACI gatekeeper that uses anon-aadhaar to gatekeep access to valid aadhaar holders

feat(contracts): implement anon aadhaar gatekeeper

---

apps/website/package.json
pnpm-lock.yaml

Reverts privacy-scaling-explorations/maci#1862

Revert "chore(deps): bump @mdx-js/react from 3.0.1 to 3.1.0"

---

packages/cli/ts/commands/proveOnChain.ts
packages/contracts/contracts/Tally.sol
packages/contracts/tasks/helpers/Prover.ts
packages/contracts/tests/Tally.test.ts

Need for alpha calculation in https://github.com/privacy-scaling-explorations/maci-platform/pull/353

feat(contracts): add total spent to tally

---

package.json
pnpm-lock.yaml

Reverts privacy-scaling-explorations/maci#1863

Revert "chore(deps-dev): bump typedoc-plugin-markdown from 4.2.6 to 4.2.9"

---

packages/cli/package.json
packages/contracts/package.json
packages/integrationTests/package.json
pnpm-lock.yaml

Revert hardhat dependency to fix vercel builds
N/A
N/A

revert(dev-deps): revert hardhat to 2.22.8

---

packages/contracts/contracts/Tally.sol
packages/contracts/contracts/interfaces/ITally.sol

Nove add tally results args struct to interface
N/A
N/A

chore: move add tally results args struct to interface

---

apps/website/.gitignore
apps/website/package.json
apps/website/src/pages/blogs.tsx
apps/website/src/pages/index.tsx
apps/website/src/pages/projects.tsx
apps/website/src/plugins/blog-plugin/index.ts
pnpm-lock.yaml

Fix website build
N/A
Closes #1881

fix(website): website build

---

packages/contracts/tasks/helpers/Deployment.ts
packages/contracts/tasks/runner/benchmarks.ts
packages/contracts/tasks/runner/deployFull.ts
packages/contracts/tasks/runner/deployPoll.ts
packages/contracts/tasks/runner/merge.ts
packages/contracts/ts/deploy.ts

Update deployment helper service to support different contract names.
N/A
Related to https://github.com/privacy-scaling-explorations/maci-platform/issues/433

feat(contracts): use contract names for deployment service

---

apps/website/src/content/projects.json

Add projects from ethglobal singapore to the projects page
fix #1837

chore: add ethglobal singapore projects

---

packages/contracts/tasks/helpers/Prover.ts

Ensure we do no try to access out of bound tally results

fix: ensure we pass the correct data to add tally results

---

apps/website/blog/2024-10-29-q3-review.md

docs: q3 in review blogpost

---

packages/contracts/package.json
packages/contracts/tasks/runner/submitOnChain.ts
pnpm-lock.yaml

Refactor submit onchain task
N/A
N/A

refactor(contracts): improve submit onchain task

---

.github/workflows/benchmarks.yml
.github/workflows/checks.yml
.github/workflows/circuit-build.yml
.github/workflows/codeql.yml
.github/workflows/commitlint.yml
.github/workflows/contracts-build.yml
.github/workflows/core-build.yml
.github/workflows/crypto-build.yml
.github/workflows/domainobjs-build.yml
.github/workflows/e2e.yml
.github/workflows/hardhat-tasks.yml
.github/workflows/nightly-ceremony.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/reusable-e2e.yml
.github/workflows/slither.yml
.github/workflows/subgraph-build.yml
.github/workflows/typos.yml

Use ubuntu-24.04 for the ci jobs
1. Subgraph ci job still has ubuntu-22.04 because subgraph cli doesn't support new version
2. e2e tests are failed for ubuntu-22.04 due to missing dependencies
N/A

chore: use ubuntu-24.04 for ci jobs

---

README.md

chore: fix 404 status URL

---

packages/contracts/.env.example
packages/contracts/contracts/Poll.sol
packages/contracts/package.json
packages/contracts/tests/ipfs.test.ts
packages/contracts/ts/genMaciState.ts
packages/contracts/ts/ipfs.ts
packages/contracts/ts/types.ts
pnpm-lock.yaml

This is a small part of happy offchain path.
Related to #1621 
Related to #1622

feat(contracts): add ipfs service and prepare parsing ipfs data

---

packages/cli/ts/commands/deployPoll.ts
packages/cli/ts/commands/joinPoll.ts
packages/cli/ts/index.ts
packages/cli/ts/utils/interfaces.ts
packages/contracts/contracts/MACI.sol
packages/contracts/contracts/Poll.sol
packages/contracts/contracts/interfaces/IPoll.sol
packages/contracts/contracts/interfaces/ISignUpGatekeeper.sol
packages/contracts/contracts/utilities/Params.sol
packages/contracts/deploy-config-example.json
packages/contracts/tasks/deploy/poll/01-gatekeepers.ts
packages/contracts/tasks/deploy/poll/02-poll.ts
packages/contracts/tasks/helpers/constants.ts
packages/contracts/tests/MACI.test.ts
packages/contracts/tests/MessageProcessor.test.ts
packages/contracts/tests/Poll.test.ts
packages/contracts/tests/PollFactory.test.ts
packages/contracts/tests/Tally.test.ts
packages/contracts/tests/TallyNonQv.test.ts
packages/contracts/tests/constants.ts
packages/integrationTests/ts/__tests__/maci-keys.test.ts
packages/integrationTests/ts/__tests__/utils/interfaces.ts
packages/integrationTests/ts/__tests__/utils/utils.ts

Use a gatekeeper per each poll so that each can have its own gatekeeping (maci level more general, poll more specific)
fix #1858

feat: use gatekeeper per poll

---

apps/website/versioned_docs/version-v2.x/contributing/contributing.md

Update contribution guidelines

docs: update contribution guidelines

---

packages/circuits/circom/anon/pollJoining.circom
packages/circuits/circom/circuits.json
packages/circuits/ts/__tests__/PollJoining.test.ts
packages/circuits/ts/types.ts
packages/cli/ts/commands/joinPoll.ts
packages/contracts/contracts/MACI.sol
packages/contracts/contracts/Poll.sol
packages/contracts/contracts/PollFactory.sol
packages/contracts/contracts/interfaces/IPollFactory.sol
packages/contracts/tests/PollFactory.test.ts
packages/core/ts/Poll.ts
packages/core/ts/utils/types.ts

Currently, the nullifier leaks user identity between polls, as it's the poseidon hash of the user original private key. By adding the poll Id as a public input, we can check inside the circuit that nullifier = poseidon(privateKey, pollId), thus resulting in completely different nullifiers per each poll, and also keeping the use of the nullifier to prevent double signup.

feat: make nullifier not leak identity between polls

---

.github/workflows/relayer-build.yml
apps/relayer/.env.example
apps/relayer/.eslintrc.cjs
apps/relayer/.gitignore
apps/relayer/README.md
apps/relayer/hardhat.config.cjs
apps/relayer/nest-cli.json
apps/relayer/package.json
apps/relayer/tests/app.test.ts
apps/relayer/ts/app.module.ts
apps/relayer/ts/jest/setup.ts
apps/relayer/ts/jest/transform.js
apps/relayer/ts/main.ts
apps/relayer/tsconfig.build.json
apps/relayer/tsconfig.json
pnpm-lock.yaml

This is a part of happy offchain path support.
Next PRs will contain more specific features.
Related to [#279](https://github.com/privacy-scaling-explorations/maci-platform/issues/279)

feat(relayer): add relayer service boilerplate

---

apps/relayer/package.json
apps/relayer/tests/messages.test.ts
apps/relayer/ts/app.module.ts
apps/relayer/ts/message/__tests__/message.controller.test.ts
apps/relayer/ts/message/__tests__/message.service.test.ts
apps/relayer/ts/message/__tests__/utils.ts
apps/relayer/ts/message/__tests__/validation.test.ts
apps/relayer/ts/message/dto.ts
apps/relayer/ts/message/message.controller.ts
apps/relayer/ts/message/message.module.ts
apps/relayer/ts/message/message.service.ts
apps/relayer/ts/message/types.ts
apps/relayer/ts/message/validation.ts
pnpm-lock.yaml

This is a part of happy offchain path
> [!IMPORTANT]

feat(relayer): add publish message api method

---

packages/contracts/contracts/Poll.sol
packages/contracts/contracts/PollFactory.sol
packages/contracts/tests/Poll.test.ts

Poll init is redundant so it can be removed to simplify the code
(needs #1854 merged first and new anon poll joining artifacts built)

refactor: remove redundant init from poll contract

---

apps/website/versioned_docs/version-v2.x/contributing/contributing.md
apps/website/versioned_docs/version-v2.x/core-concepts/maci-keys.md

- Adds MACI key generation steps to docs
- Corrects a typo in contributing guidlines
> [!IMPORTANT]

docs: add MACI key generation instructions and typo correction

---

.github/workflows/relayer-build.yml
apps/relayer/.env.example
apps/relayer/package.json
apps/relayer/tests/app.test.ts
apps/relayer/tests/messages.test.ts
apps/relayer/ts/app.module.ts
apps/relayer/ts/jest/mongo.ts
apps/relayer/ts/message/__tests__/message.repository.test.ts
apps/relayer/ts/message/__tests__/message.service.test.ts
apps/relayer/ts/message/__tests__/utils.ts
apps/relayer/ts/message/message.controller.ts
apps/relayer/ts/message/message.module.ts
apps/relayer/ts/message/message.repository.ts
apps/relayer/ts/message/message.schema.ts
apps/relayer/ts/message/message.service.ts
apps/relayer/ts/message/validation.ts
apps/relayer/ts/messageBatch/__tests__/messageBatch.repository.test.ts
apps/relayer/ts/messageBatch/__tests__/messageBatch.service.test.ts
apps/relayer/ts/messageBatch/__tests__/utils.ts
apps/relayer/ts/messageBatch/__tests__/validation.test.ts
apps/relayer/ts/messageBatch/dto.ts
apps/relayer/ts/messageBatch/messageBatch.module.ts
apps/relayer/ts/messageBatch/messageBatch.repository.ts
apps/relayer/ts/messageBatch/messageBatch.schema.ts
apps/relayer/ts/messageBatch/messageBatch.service.ts
apps/relayer/ts/messageBatch/validation.ts
pnpm-lock.yaml

This is a part of happy offchain path feature
> [!IMPORTANT]

feat(relayer): add database integration

---

packages/circuits/circom/anon/pollJoining.circom
packages/circuits/ts/__tests__/PollJoining.test.ts
packages/circuits/ts/__tests__/ProcessMessages.test.ts
packages/circuits/ts/__tests__/TallyVotes.test.ts
packages/circuits/ts/types.ts
packages/cli/tests/e2e/e2e.test.ts
packages/cli/tests/e2e/keyChange.test.ts
packages/cli/tests/unit/joinPoll.test.ts
packages/cli/ts/commands/joinPoll.ts
packages/cli/ts/index.ts
packages/cli/ts/utils/interfaces.ts
packages/core/ts/Poll.ts
packages/core/ts/utils/types.ts
packages/integrationTests/ts/__tests__/integration.test.ts

Revert joining polls with a new key to improve privacy vs coordinator, with forcing the use of one key to reduce the risk of key selling, as keys would now be reused within polls.
> [!IMPORTANT]

feat: force the same key for each poll

---

packages/circuits/circom/anon/poll.circom
packages/circuits/circom/circuits.json
packages/circuits/package.json
packages/circuits/ts/__tests__/PollJoined.test.ts
packages/circuits/ts/types.ts
packages/cli/tests/ceremony-params/ceremonyParams.test.ts
packages/cli/tests/constants.ts
packages/cli/ts/commands/checkVerifyingKeys.ts
packages/cli/ts/commands/extractVkToFile.ts
packages/cli/ts/commands/joinPoll.ts
packages/cli/ts/commands/setVerifyingKeys.ts
packages/cli/ts/index.ts
packages/cli/ts/utils/interfaces.ts
packages/contracts/contracts/Poll.sol
packages/contracts/contracts/VkRegistry.sol
packages/contracts/contracts/interfaces/IVkRegistry.sol
packages/contracts/deploy-config-example.json
packages/contracts/tasks/deploy/maci/08-vkRegistry.ts
packages/contracts/tests/Poll.test.ts
packages/contracts/tests/Tally.test.ts
packages/contracts/tests/VkRegistry.test.ts
packages/contracts/tests/constants.ts
packages/core/ts/Poll.ts
packages/core/ts/index.ts
packages/core/ts/utils/types.ts
packages/core/ts/utils/utils.ts
packages/integrationTests/ts/__tests__/integration.test.ts

Add poll joined circuit
This is a part of happy offchain path
> [!IMPORTANT]

feat(circuits): add poll joined circuit

---

packages/cli/tests/e2e/e2e.test.ts
packages/integrationTests/ts/__tests__/data/suites.json

Remove redundant e2e/integration steps. 
First part in the refactoring of tests which will unify the test suite to make it more maintainable 
re #2141 
> [!IMPORTANT]

test: remove redundant tests and cleanup

---

packages/contracts/contracts/Poll.sol
packages/contracts/contracts/VkRegistry.sol
packages/contracts/contracts/interfaces/IVkRegistry.sol
packages/contracts/tests/Poll.test.ts
packages/contracts/tests/Tally.test.ts
packages/contracts/tests/VkRegistry.test.ts
packages/core/ts/utils/utils.ts
packages/sdk/ts/keys/verifyingKeys.ts

Remove redundant voteOptionThreeDepth param form pollJoined and pollJoining VkRegistry signatures
> [!IMPORTANT]

refactor: remove redundant param

---

packages/cli/ts/commands/genProofs.ts
packages/sdk/ts/proof/generate.ts
packages/sdk/ts/proof/index.ts
packages/sdk/ts/proof/types.ts

The previous `generateProofs` function was returning only `tallyData` but `processProofs` and `tallyProofs` were missing. The coordinator service was built using these two missing variables so I needed to return them in the sdk function. By using an interface, we are not modifying the function usage to much (instead of `const tallyData = await generateProofs( ... )` we use `const { tallyData } = await generateProofs( ... )`
> [!IMPORTANT]

Return processProofs, tallyProofs and tallyData in generateProofs function

---

packages/testing/ts/__tests__/unit/fundWallet.test.ts
packages/testing/ts/__tests__/unit/timeTravel.test.ts

Move tests over to testing package as they require hardhat which is not configured in maci-sdk
> [!IMPORTANT]

test: move tests over to testing package

---

packages/cli/ts/index.ts
packages/contracts/ts/genMaciState.ts
packages/contracts/ts/types.ts
packages/sdk/ts/maci/state.ts
packages/sdk/ts/maci/types.ts

This PR adds functionality to preserve logs fetched during `genMaciState()` execution by saving them to a file. The logs contain all on-chain actions and related metadata, which can be useful for debugging and auditing purposes in MACI rounds.
The implementation adds:
- A new parameter `logsOutputPath` to the relevant interfaces and function signatures
- Logic to save the fetched logs to a specified file path
- A new CLI option `--logs-output`/`-l` to specify where logs should be saved
Users can now run `maci-cli genLocalState` with the new `-l` option to save logs:
```
maci-cli genLocalState -p <pollId> -o <stateOutputPath> -l <logsOutputPath>
```
The logs are saved in JSON format and include:
- Metadata (MACI address, poll ID, block range, timestamp)
- A complete record of all actions …

 feat(core): preserve logs fetched during genMaciState execution

---

packages/contracts/ts/proofs.ts
packages/sdk/ts/proof/__tests__/download.test.ts
packages/sdk/ts/proof/constants.ts
packages/sdk/ts/proof/download.ts
packages/sdk/ts/proof/types.ts

Allow to download zkey and wasm on browsers for the poll joining circuit
> [!IMPORTANT]

feat: allow to download artifacts on browser

---

apps/website/src/scripts/setupSolidityDocs.ts
packages/contracts/contracts/mocks/Mocker.sol

Ensure SolidityDocs are correctly displayed on the doc website
> [!IMPORTANT]

docs: ensure solidity docs are displayed

---

.github/workflows/relayer-build.yml
.github/workflows/reusable-e2e.yml

Always download zkeys instead of caching
N/A
N/A
> [!IMPORTANT]

fix: remove caching zkeys for downloading

---

packages/contracts/tasks/deploy/poll/03-poll.ts
packages/contracts/tasks/helpers/types.ts

When running `pnpm deploy-poll:<NETWORK>` in the `packages/contracts` with a voice credit proxy different than `ConstantInitialVoiceCreditProxy`  I was getting an error saying that the contract was not saved. 
1. check if a specific initialVoiceCreditProxy is set in `deploy-config.json`. If there is none, use the `ConstantInitialVoiceCreditProxy`. Fetch that contract from the saved list (it should exist because it is deployed in the previous step `01-voiceCreditProxy.ts`
2. change **erc20Votes** by **erc20votes** in `@excubiae/contracts/contracts/extensions/erc20votes/` according to how it is spelled in the excubiae repository
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical …

fix(contracts): deploy poll with specified voice credit

---

packages/sdk/ts/tally/index.ts
packages/sdk/ts/tally/results.ts
packages/sdk/ts/tally/types.ts

Add SDK functions to get tally results from the Tally contract
fix #2413 
> [!IMPORTANT]

feat(sdk): get results from tally contract

---

packages/sdk/ts/browser/index.ts
packages/sdk/ts/browser/joinPoll.ts
packages/sdk/ts/trees/index.ts
packages/sdk/ts/trees/stateTree.ts
packages/sdk/ts/trees/types.ts
packages/sdk/ts/user/index.ts
packages/sdk/ts/user/types.ts
packages/sdk/ts/user/utils.ts
packages/testing/ts/__tests__/unit/joinPoll.test.ts

Allow to join poll using by passing an already calculated inclusion proof
> [!IMPORTANT]

feat(sdk): allow to reuse inclusion proof for joinPoll

---

packages/cli/ts/index.ts

Remove duplicate CLI flag
> [!IMPORTANT]

fix(cli): adjust duplicate cli flag

---

apps/website/versioned_docs/version-v3.x/quick-start.md
packages/contracts/tasks/runner/prove.ts

* Allow parent directories when creating a prove output directory
* Small modifications to Getting Started guide to provide additional info on commands
* Use same directory structure in guide - some commands in the guide used different file paths for proof output directory 
The gettting started guide uses nested directories for outputting results. `mkdir` requires a -p flag in order to do this. You can do this by adding the `recursive` option:
```ts
// from this
await fs.promises.mkdir(outputDir);
// to this
await fs.promises.mkdir(outputDir, { recursive: true });
```
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while appreciated, are not a …

fix: allow parent directories for prove output dir

---

apps/subgraph/config/network.json
apps/subgraph/schemas/schema.v1.graphql
packages/sdk/ts/browser/index.ts
packages/sdk/ts/index.ts
packages/sdk/ts/subgraph/index.ts
packages/sdk/ts/subgraph/maciSubgraph.ts
packages/sdk/ts/subgraph/types.ts
packages/sdk/ts/trees/index.ts
packages/sdk/ts/trees/stateTree.ts

Implement a MaciSubgraph class which allows to fetch all signed up public keys
> [!IMPORTANT]

feat(sdk): implement Subgraph fetcher for signup tree

---

apps/website/versioned_docs/version-v3.x/technical-references/zk-snark-circuits/setup.md
packages/sdk/ts/vote/invalidate.ts

Ensure we can invalidate votes by using the right nonce for the command to invalidate
> [!IMPORTANT]

fix: ensure invalidVotes uses the correct nonce

---

packages/contracts/tasks/runner/prove.ts
packages/contracts/tasks/runner/submitOnChain.ts

Do not rely on deployed-contracts.json for tally and mp addresses but use maci.polls() return value
> [!IMPORTANT]

chore(contracts): reuse pollContracts for tally and mp addresses

---

packages/sdk/ts/vote/index.ts

We want to [implement](https://github.com/privacy-scaling-explorations/maci-aragon-osx-gov-app/issues/26) a button to invalidate votes in the maci aragon demo. The `invalidateVotes` function is not exported from the sdk.
Added a follow up [issue](https://github.com/privacy-scaling-explorations/maci/issues/2517) to add tests for `invalidateVotes` as I can't see it used in any tests
> [!IMPORTANT]

chore: expose sdk function invalidateVotes

---

pnpm-lock.yaml

Resolve parsing issue for dependabot for pnpm-lock.yaml
Probably related to dependabot PRs merged at the same time, blocks to create new dependabot PRs
N/A
> [!IMPORTANT]

fix: resolve parsing issue for pnpm-lock.yaml

---

apps/coordinator/tests/e2e.redis.test.ts
apps/coordinator/ts/redis/__tests__/redis.service.test.ts
apps/coordinator/ts/redis/types.ts
apps/coordinator/ts/redis/utils.ts

1. update tests and examples were missing in the redis module. To end up with this particular implementation I had to consider a couple of things.
1.1. The `redis` package does not have an `update` function. It only has `set` and `delete`
1.2. I first tried to implement an `update` function that would use a redis transaction to execute `delete` and `set`. That way we would guarantee that all deleted values would get replaced by the new values. 
1.3. I realized that `set` can be used as an update function by passing the same key.
```javascript
this.service.set(key, value1); // set or create a new registry in Redis db
// ...
this.service.set(key, value2); // update current registry with new value
2. Created a `IIdentityScheduledPoll ` that contains the minimal properties required to …
```

feat(coordinator): update function in redis + adapt tests and utils

---

packages/sdk/ts/subgraph/maciSubgraph.ts

The `users` subgraph query previously did not guarantee the order of returned users, which could lead to inconsistencies.
- Added `orderBy: createdAt` and `orderDirection: asc` to the users query that ensures users are returned in the order of their signup (ascending).
This ordering is necessary to correctly generate the signup tree when using `generateSignupTreeFromKeys`, which expects users in the exact order they signed up.
> [!IMPORTANT]

fix(sdk): sort users by creation date in subgraph query

---

packages/sdk/ts/subgraph/maciSubgraph.ts

Updated the `getKeys` function to include the known padKey as the first entry in the returned list of public keys to correctly generate signUpTree using `generateSignUpTreeFromKeys`
Modified `getKeys` to prepend the known padKey to the list of public keys fetched from the subgraph.
The signup tree always starts with a `padKey`, but since there’s no on-chain event for its insertion, it isn’t included in subgraph results. This change ensures that downstream consumers like `generateSignupTreeFromKeys` receive a complete list, including the `padKey`, without having to handle it separately.
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) unless they significantly improve clarity in technical documentation. These contributions, while …

fix(sdk): add padKey to array of retrieved MACI public keys

---

packages/contracts/.env.example
packages/sdk/ts/browser/index.ts
packages/sdk/ts/user/types.ts

1. Export `EMode` to be used in external apps
2. Export user types to be used in external apps
3. Small fix in the .env.example comment
> [!IMPORTANT]

feat(sdk): export EMode + user types

---

.github/workflows/nightly-ceremony.yml
.github/workflows/nightly-coordinator-e2e.yml
.github/workflows/nightly-mac.yml
.github/workflows/nightly.yml
apps/website/versioned_docs/version-v3.x/contributing/contributing.md

Add webhook notification for scheduled jobs and add some improvements for contribution guide
Blocked by https://github.com/privacy-scaling-explorations/maci/pull/2727
N/A
> [!IMPORTANT]

chore: add webhook notification for scheduled jobs

---

apps/coordinator/ts/deployer/__tests__/utils.ts
apps/coordinator/ts/deployer/deployer.service.ts

Allow users to send pre-existing deployed contract addresses of poseidon contracts to avoid redeploying them again. Please be sure that the nightly coordinator e2e tests are working correctly before merging this.
> [!IMPORTANT]

fix(coordinator): allow reuse of poseidon addresses
